/**
 * Identity Security Cloud API - Entitlement Connections
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntitlementConnectionSearchHitEntitlement } from './entitlementConnectionSearchHitEntitlement';


/**
 * Entitlement connection record returned by search-backed list endpoints.
 */
export interface EntitlementConnectionSearchHit { 
    /**
     * Connection ID as represented in search results.
     */
    id?: string;
    /**
     * Identity summary object from search index.
     */
    identity?: { [key: string]: any; };
    /**
     * Machine identity summary object when available.
     */
    machineIdentity?: { [key: string]: any; };
    /**
     * Account summary object.
     */
    account?: { [key: string]: any; };
    entitlement?: EntitlementConnectionSearchHitEntitlement;
    /**
     * Source summary object.
     */
    source?: { [key: string]: any; };
    /**
     * Connection state object.
     */
    state?: { [key: string]: any; };
    /**
     * JIT timestamps for lifecycle events.
     */
    jit?: { [key: string]: any; };
    /**
     * Indicates whether the connection is marked as standalone.
     */
    standalone?: boolean;
    /**
     * Connection type classification.
     */
    type?: EntitlementConnectionSearchHitTypeEnum;
}
export enum EntitlementConnectionSearchHitTypeEnum {
    Jit = 'JIT',
    Standing = 'STANDING',
    Na = 'NA'
};



