/**
 * Identity Security Cloud API - SOD Policies
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccessCriteriaCriteriaListInner { 
    /**
     * Type of the propery to which this reference applies to
     */
    type?: AccessCriteriaCriteriaListInnerTypeEnum;
    /**
     * ID of the object to which this reference applies to
     */
    id?: string;
    /**
     * Human-readable display name of the object to which this reference applies to
     */
    name?: string;
}
export enum AccessCriteriaCriteriaListInnerTypeEnum {
    Entitlement = 'ENTITLEMENT'
};



