/**
 * Identity Security Cloud API - JIT Activations
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivationWorkflowStatus } from './activationWorkflowStatus';


export interface JitActivationActivateResponse { 
    /**
     * Workflow or business identifier for this activation.
     */
    id: string;
    /**
     * Persistent activation record identifier for this JIT activation.
     */
    activationId: string;
    /**
     * Entitlement connection identifier for the activation.
     */
    connectionId: string;
    /**
     * Activation duration in minutes for this workflow.
     */
    activationPeriodMins: number;
    status: ActivationWorkflowStatus;
    /**
     * Time when the activation workflow was started (ISO-8601).
     */
    startTime: string;
}



