/**
 * Identity Security Cloud API - Access Profiles
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccessprofilemetadatabulkupdatebyidrequestValuesInner } from './accessprofilemetadatabulkupdatebyidrequestValuesInner';


/**
 * Request to bulk update Access Model Metadata on a list of access profiles identified by ID. The maximum access profile count in a single request is 3000. A single access profile cannot be assigned more than 25 metadata values. Adding or replacing custom metadata requires a suite license.
 */
export interface Accessprofilemetadatabulkupdatebyidrequest { 
    /**
     * The IDs of the access profiles to update.
     */
    accessProfiles: Array<string>;
    /**
     * The operation to be performed
     */
    operation: AccessprofilemetadatabulkupdatebyidrequestOperationEnum;
    /**
     * The choice of update scope. **ATTRIBUTE** replaces only the values of the attributes named in `values`, and **ALL** replaces every metadata attribute on the access profile.
     */
    replaceScope: AccessprofilemetadatabulkupdatebyidrequestReplaceScopeEnum;
    /**
     * The metadata to be updated, including attribute key and value.
     */
    values: Array<AccessprofilemetadatabulkupdatebyidrequestValuesInner>;
}
export enum AccessprofilemetadatabulkupdatebyidrequestOperationEnum {
    Add = 'ADD',
    Remove = 'REMOVE',
    Replace = 'REPLACE'
};
export enum AccessprofilemetadatabulkupdatebyidrequestReplaceScopeEnum {
    All = 'ALL',
    Attribute = 'ATTRIBUTE'
};



