/**
 * Identity Security Cloud API - Access Profiles
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributeDTO } from './attributeDTO';


export interface AttributeDTOList { 
    attributes?: Array<AttributeDTO> | null;
}

