/**
 * Identity Security Cloud API - Access Profiles
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProvisioningCriteriaOperation } from './provisioningCriteriaOperation';


/**
 * Defines matching criteria for an account to be provisioned with a specific access profile.
 */
export interface ProvisioningCriteriaLevel3 { 
    operation?: ProvisioningCriteriaOperation;
    /**
     * Name of the account attribute to be tested. If **operation** is one of `EQUALS`, `NOT_EQUALS`, `CONTAINS`, or `HAS`, this field is required. Otherwise, specifying it results in an error.
     */
    attribute?: string | null;
    /**
     * String value to test the account attribute w/r/t the specified operation. If the operation is one of `EQUALS`, `NOT_EQUALS`, or `CONTAINS`, this field is required. Otherwise, specifying it results in an error. If the attribute is not string-typed, the API will convert it to the appropriate type.
     */
    value?: string | null;
    /**
     * Array of child criteria. This field is required if the operation is `AND` or `OR`. Otherwise, it must be left null. A maximum of three levels of criteria are supported, including leaf nodes.
     */
    children?: string | null;
}



