/**
 * Identity Security Cloud API - SIM Integrations
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This is a reference to a plan initializer script.
 */
export interface ProvisioningConfigPlanInitializerScript { 
    /**
     * This is a Rule that allows provisioning instruction changes.
     */
    source?: string;
}

