/**
 * Identity Security Cloud API - Workflows
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The identity that owns the workflow.  The owner\'s permissions in IDN will determine what actions the workflow is allowed to perform.  Ownership can be changed by updating the owner in a PUT or PATCH request.
 */
export interface WorkflowBodyOwner { 
    /**
     * The type of object that is referenced
     */
    type?: WorkflowBodyOwnerTypeEnum;
    /**
     * The unique ID of the object
     */
    id?: string;
    /**
     * The name of the object
     */
    name?: string;
}
export enum WorkflowBodyOwnerTypeEnum {
    Identity = 'IDENTITY'
};



