/**
 * Identity Security Cloud API - Workflows
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkflowOAuthClient { 
    /**
     * OAuth client ID for the trigger. This is a UUID generated upon creation.
     */
    id?: string;
    /**
     * OAuthClient secret.
     */
    secret?: string;
    /**
     * URL for the external trigger to invoke
     */
    url?: string;
}

