/**
 * Identity Security Cloud API - SOD Violations
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExceptionCriteriaCriteriaListInner } from './exceptionCriteriaCriteriaListInner';


export interface ExceptionCriteria { 
    /**
     * List of exception criteria. There is a min of 1 and max of 50 items in the list.
     */
    criteriaList?: Array<ExceptionCriteriaCriteriaListInner>;
}

