/**
 * Identity Security Cloud API - SOD Violations
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdentityWithNewAccessAccessRefsInner } from './identityWithNewAccessAccessRefsInner';


/**
 * An identity with a set of access to be added
 */
export interface IdentityWithNewAccess { 
    /**
     * Identity id to be checked.
     */
    identityId: string;
    /**
     * The list of access items to consider for possible violations in a preventive check. Supported types are ENTITLEMENT, ACCESS_PROFILE, and ROLE.
     */
    accessRefs: Array<IdentityWithNewAccessAccessRefsInner>;
}

