/**
 * Identity Security Cloud API - SP-Config
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ObjectExportImportOptions { 
    /**
     * Object ids to be included in an import or export.
     */
    includedIds?: Array<string>;
    /**
     * Object names to be included in an import or export.
     */
    includedNames?: Array<string>;
}

