/**
 * Identity Security Cloud API - SP-Config
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SpConfigImportJobStatus { 
    /**
     * Unique id assigned to this job.
     */
    jobId: string;
    /**
     * Status of the job.
     */
    status: SpConfigImportJobStatusStatusEnum;
    /**
     * Type of the job, either export or import.
     */
    type: SpConfigImportJobStatusTypeEnum;
    /**
     * The time until which the artifacts will be available for download.
     */
    expiration?: string;
    /**
     * The time the job was started.
     */
    created: string;
    /**
     * The time of the last update to the job.
     */
    modified: string;
    /**
     * This message contains additional information about the overall status of the job.
     */
    message?: string;
    /**
     * The time the job was completed.
     */
    completed?: string;
}
export enum SpConfigImportJobStatusStatusEnum {
    NotStarted = 'NOT_STARTED',
    InProgress = 'IN_PROGRESS',
    Complete = 'COMPLETE',
    Cancelled = 'CANCELLED',
    Failed = 'FAILED'
};
export enum SpConfigImportJobStatusTypeEnum {
    Export = 'EXPORT',
    Import = 'IMPORT'
};



