/**
 * Identity Security Cloud API - Entitlements
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EntitlementV2PrivilegeLevel { 
    /**
     * Direct privilege level assigned to the entitlement
     */
    direct?: EntitlementV2PrivilegeLevelDirectEnum;
    /**
     * User or process that set the privilege level
     */
    setBy?: string;
    /**
     * Method by which the privilege level was set
     */
    setByType?: EntitlementV2PrivilegeLevelSetByTypeEnum | null;
    /**
     * Inherited privilege level on the entitlement, if any
     */
    inherited?: EntitlementV2PrivilegeLevelInheritedEnum | null;
    /**
     * Effective privilege level assigned to the entitlement
     */
    effective?: EntitlementV2PrivilegeLevelEffectiveEnum;
}
export enum EntitlementV2PrivilegeLevelDirectEnum {
    High = 'HIGH',
    Low = 'LOW',
    Medium = 'MEDIUM',
    None = 'NONE'
};
export enum EntitlementV2PrivilegeLevelSetByTypeEnum {
    Override = 'OVERRIDE',
    CustomCriteria = 'CUSTOM_CRITERIA',
    ConnectorCriteria = 'CONNECTOR_CRITERIA',
    SingleLevelCriteria = 'SINGLE_LEVEL_CRITERIA'
};
export enum EntitlementV2PrivilegeLevelInheritedEnum {
    High = 'HIGH',
    Low = 'LOW',
    Medium = 'MEDIUM',
    None = 'NONE'
};
export enum EntitlementV2PrivilegeLevelEffectiveEnum {
    High = 'HIGH',
    Low = 'LOW',
    Medium = 'MEDIUM',
    None = 'NONE'
};



