/**
 * Identity Security Cloud API - Entitlements
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccessModelMetadata } from './accessModelMetadata';


/**
 * Additional data to classify the entitlement
 */
export interface EntitlementV2AccessModelMetadata { 
    attributes?: Array<AccessModelMetadata>;
}

