/**
 * Identity Security Cloud API - Work Items
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FormItemDetails { 
    /**
     * Name of the FormItem
     */
    name?: string | null;
}

