/**
 * Identity Security Cloud API - Work Items
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The state of a work item
 */
export enum WorkItemState {

    Finished = 'Finished',

    Rejected = 'Rejected',

    Returned = 'Returned',

    Expired = 'Expired',

    Pending = 'Pending',

    Canceled = 'Canceled'
}

