/**
 * Identity Security Cloud API - Identity Profiles
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdentityProfile } from './identityProfile';
import { IdentityProfileExportedObjectSelf } from './identityProfileExportedObjectSelf';


/**
 * Identity profile exported object.
 */
export interface IdentityProfileExportedObject { 
    /**
     * Version or object from the target service.
     */
    version?: number;
    self?: IdentityProfileExportedObjectSelf;
    object?: IdentityProfile;
}

