/**
 * Identity Security Cloud API - Connector Rule Management
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SourceCode } from './sourceCode';
import { ConnectorRuleCreateRequestSignature } from './connectorRuleCreateRequestSignature';


/**
 * ConnectorRuleResponse
 */
export interface ConnectorRuleResponse { 
    /**
     * the name of the rule
     */
    name: string;
    /**
     * a description of the rule\'s purpose
     */
    description?: string | null;
    /**
     * the type of rule
     */
    type: ConnectorRuleResponseTypeEnum;
    signature?: ConnectorRuleCreateRequestSignature;
    sourceCode: SourceCode;
    /**
     * a map of string to objects
     */
    attributes?: object | null;
    /**
     * the ID of the rule
     */
    id: string;
    /**
     * an ISO 8601 UTC timestamp when this rule was created
     */
    created: string;
    /**
     * an ISO 8601 UTC timestamp when this rule was last modified
     */
    modified?: string | null;
}
export enum ConnectorRuleResponseTypeEnum {
    BuildMap = 'BuildMap',
    ConnectorAfterCreate = 'ConnectorAfterCreate',
    ConnectorAfterDelete = 'ConnectorAfterDelete',
    ConnectorAfterModify = 'ConnectorAfterModify',
    ConnectorBeforeCreate = 'ConnectorBeforeCreate',
    ConnectorBeforeDelete = 'ConnectorBeforeDelete',
    ConnectorBeforeModify = 'ConnectorBeforeModify',
    JdbcBuildMap = 'JDBCBuildMap',
    JdbcOperationProvisioning = 'JDBCOperationProvisioning',
    JdbcProvision = 'JDBCProvision',
    PeopleSoftHrmsBuildMap = 'PeopleSoftHRMSBuildMap',
    PeopleSoftHrmsOperationProvisioning = 'PeopleSoftHRMSOperationProvisioning',
    PeopleSoftHrmsProvision = 'PeopleSoftHRMSProvision',
    RacfPermissionCustomization = 'RACFPermissionCustomization',
    ResourceObjectCustomization = 'ResourceObjectCustomization',
    SapBuildMap = 'SAPBuildMap',
    SapHrManagerRule = 'SapHrManagerRule',
    SapHrOperationProvisioning = 'SapHrOperationProvisioning',
    SapHrProvision = 'SapHrProvision',
    SuccessFactorsOperationProvisioning = 'SuccessFactorsOperationProvisioning',
    WebServiceAfterOperationRule = 'WebServiceAfterOperationRule',
    WebServiceBeforeOperationRule = 'WebServiceBeforeOperationRule',
    ResourceObjectCustomization2 = 'ResourceObjectCustomization'
};



