/**
 * Identity Security Cloud API - IAI Outliers
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OutlierFeatureTranslation } from './outlierFeatureTranslation';
import { OutlierValueType } from './outlierValueType';


export interface OutlierContributingFeature { 
    /**
     * Contributing feature id
     */
    id?: string;
    /**
     * The name of the feature
     */
    name?: string;
    valueType?: OutlierValueType;
    /**
     * The feature value
     */
    value?: number;
    /**
     * The importance of the feature. This can also be a negative value
     */
    importance?: number;
    /**
     * The (translated if header is passed) displayName for the feature
     */
    displayName?: string;
    /**
     * The (translated if header is passed) description for the feature
     */
    description?: string;
    translationMessages?: OutlierFeatureTranslation | null;
}

