/**
 * Identity Security Cloud API - IAI Outliers
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OutliersContributingFeatureAccessItems { 
    /**
     * The ID of the access item
     */
    id?: string;
    /**
     * the display name of the access item
     */
    displayName?: string;
    /**
     * Description of the access item.
     */
    description?: string | null;
    /**
     * The type of the access item.
     */
    accessType?: OutliersContributingFeatureAccessItemsAccessTypeEnum;
    /**
     * the associated source name if it exists
     */
    sourceName?: string;
    /**
     * rarest access
     */
    extremelyRare?: boolean;
}
export enum OutliersContributingFeatureAccessItemsAccessTypeEnum {
    Entitlement = 'ENTITLEMENT',
    AccessProfile = 'ACCESS_PROFILE',
    Role = 'ROLE'
};



