/**
 * Identity Security Cloud API - IAI Outliers
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TranslationMessage { 
    /**
     * The key of the translation message
     */
    key?: string;
    /**
     * The values corresponding to the translation messages
     */
    values?: Array<string>;
}

