/**
 * Identity Security Cloud API - Configuration Hub
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduledActionResponseContentBackupOptionsObjectOptionsValue } from './scheduledActionResponseContentBackupOptionsObjectOptionsValue';


/**
 * Options for BACKUP type jobs. Required for BACKUP jobs.
 */
export interface ScheduledActionPayloadContentBackupOptions { 
    /**
     * Object types that are to be included in the backup.
     */
    includeTypes?: Array<string>;
    /**
     * Map of objectType string to the options to be passed to the target service for that objectType.
     */
    objectOptions?: { [key: string]: ScheduledActionResponseContentBackupOptionsObjectOptionsValue; };
}

