/**
 * Identity Security Cloud API - Application Discovery
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Discovered applications with their respective associated sources
 */
export interface FullDiscoveredApplications { 
    /**
     * Unique identifier for the discovered application.
     */
    id?: string;
    /**
     * Name of the discovered application.
     */
    name?: string;
    /**
     * Source from which the application was discovered.
     */
    discoverySource?: string;
    /**
     * The vendor associated with the discovered application.
     */
    discoveredVendor?: string;
    /**
     * A brief description of the discovered application.
     */
    description?: string;
    /**
     * List of recommended connectors for the application.
     */
    recommendedConnectors?: Array<string>;
    /**
     * The timestamp when the application was last received via an entitlement aggregation invocation  or a manual csv upload, in ISO 8601 format.
     */
    discoveredAt?: string;
    /**
     * The timestamp when the application was first discovered, in ISO 8601 format.
     */
    createdAt?: string;
    /**
     * The status of an application within the discovery source.  By default this field is set to \"ACTIVE\" when the application is discovered.  If an application has been deleted from within the discovery source, the status will be set to \"INACTIVE\".
     */
    status?: string;
    /**
     * List of associated sources related to this discovered application.
     */
    associatedSources?: Array<string>;
    /**
     * The operational status of the application.
     */
    operationalStatus?: string;
    /**
     * The category of the discovery source.
     */
    discoverySourceCategory?: string;
    /**
     * The number of licenses associated with the application.
     */
    licenseCount?: number;
    /**
     * Indicates whether the application is sanctioned.
     */
    isSanctioned?: boolean;
    /**
     * URL of the application\'s logo.
     */
    logo?: string;
    /**
     * The URL of the application.
     */
    appUrl?: string;
    /**
     * List of groups associated with the application.
     */
    groups?: Array<object>;
    /**
     * The count of users associated with the application.
     */
    usersCount?: string;
    /**
     * The owners of the application.
     */
    applicationOwner?: Array<string>;
    /**
     * The IT owners of the application.
     */
    itApplicationOwner?: Array<string>;
    /**
     * The business criticality level of the application.
     */
    businessCriticality?: string;
    /**
     * The data classification level of the application.
     */
    dataClassification?: string;
    /**
     * The business unit associated with the application.
     */
    businessUnit?: string;
    /**
     * The installation type of the application.
     */
    installType?: string;
    /**
     * The environment in which the application operates.
     */
    environment?: string;
    /**
     * The risk score of the application ranging from 0-100, 100 being highest risk.
     */
    riskScore?: number;
    /**
     * Indicates whether the application is used for business purposes.
     */
    isBusiness?: boolean;
    /**
     * The total number of sign-in accounts for the application.
     */
    totalSigninsCount?: number;
    /**
     * The risk level of the application.
     */
    riskLevel?: FullDiscoveredApplicationsRiskLevelEnum;
    /**
     * Indicates whether the application has privileged access.
     */
    isPrivileged?: boolean;
    /**
     * The warranty expiration date of the application.
     */
    warrantyExpiration?: string;
    /**
     * Additional attributes of the application useful for visibility of governance posture.
     */
    attributes?: object;
}
export enum FullDiscoveredApplicationsRiskLevelEnum {
    High = 'High',
    Medium = 'Medium',
    Low = 'Low'
};



