/**
 * Identity Security Cloud API - Application Discovery
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FullDiscoveredApplications } from './fullDiscoveredApplications';
import { SlimDiscoveredApplications } from './slimDiscoveredApplications';


/**
 * @type GetDiscoveredApplicationsV1200ResponseInner
 * @export
 */
export type GetDiscoveredApplicationsV1200ResponseInner = FullDiscoveredApplications | SlimDiscoveredApplications;

