/**
 * Identity Security Cloud API - Saved Search
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterType } from './filterType';
import { Range } from './range';


export interface Filter { 
    type?: FilterType;
    range?: Range;
    /**
     * The terms to be filtered.
     */
    terms?: Array<string>;
    /**
     * Indicates if the filter excludes results.
     */
    exclude?: boolean;
}



