/**
 * Identity Security Cloud API - Saved Search
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoType } from './dtoType';


/**
 * A typed reference to the object. 
 */
export interface TypedReference { 
    type: DtoType;
    /**
     * The id of the object. 
     */
    id: string;
}



