/**
 * Identity Security Cloud API - Accounts
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request used for account unlock
 */
export interface AccountUnlockRequest { 
    /**
     * If set, an external process validates that the user wants to proceed with this request.
     */
    externalVerificationId?: string;
    /**
     * If set, the IDN account is unlocked after the workflow completes.
     */
    unlockIDNAccount?: boolean;
    /**
     * If set, provisioning updates the account attribute at the source.   This option is used when the account is not synced to ensure the attribute is updated.
     */
    forceProvisioning?: boolean;
}

