/**
 * Identity Security Cloud API - Access Requests
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestedItemDetails } from './requestedItemDetails';


export interface AccessRequestTracking { 
    /**
     * The identity id in which the access request is for.
     */
    requestedFor?: string;
    /**
     * The details of the item requested.
     */
    requestedItemsDetails?: Array<RequestedItemDetails>;
    /**
     * a hash representation of the access requested, useful for longer term tracking client side.
     */
    attributesHash?: number;
    /**
     * a list of access request identifiers, generally only one will be populated, but high volume requested may result in multiple ids.
     */
    accessRequestIds?: Array<string>;
}

