/**
 * Identity Security Cloud API - Access Requests
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Describes the individual or group that is responsible for an approval step.
 */
export enum ApprovalScheme {

    AppOwner = 'APP_OWNER',

    SourceOwner = 'SOURCE_OWNER',

    Manager = 'MANAGER',

    RoleOwner = 'ROLE_OWNER',

    AccessProfileOwner = 'ACCESS_PROFILE_OWNER',

    EntitlementOwner = 'ENTITLEMENT_OWNER',

    GovernanceGroup = 'GOVERNANCE_GROUP'
}

