/**
 * Identity Security Cloud API - Access Requests
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdentityReferenceWithNameAndEmail } from './identityReferenceWithNameAndEmail';


/**
 * Configuration for approval reminder and escalation behavior. Important: Modifying this object will override the sp-approval service\'s reminderConfig and escalationConfig settings. Changes made here take precedence over any configuration set directly in the sp-approval service. 
 */
export interface ApprovalReminderAndEscalationConfig { 
    /**
     * Number of days to wait before the first reminder. If no reminders are configured, then this is the number of days to wait before escalation.
     */
    daysUntilEscalation?: number | null;
    /**
     * Number of days to wait between reminder notifications.
     */
    daysBetweenReminders?: number | null;
    /**
     * Maximum number of reminder notifications to send to the reviewer before approval escalation. The maximum allowed value is 20.
     */
    maxReminders?: number | null;
    fallbackApproverRef?: IdentityReferenceWithNameAndEmail | null;
}

