/**
 * Identity Security Cloud API - Access Requests
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request body payload for cancel access request endpoint.
 */
export interface CancelAccessRequest { 
    /**
     * This refers to the identityRequestId. To successfully cancel an access request, you must provide the identityRequestId.
     */
    accountActivityId: string;
    /**
     * Reason for cancelling the pending access request.
     */
    comment: string;
}

