/**
 * Identity Security Cloud API - Access Requests
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OwnerDto } from './ownerDto';


/**
 * Provides additional details for a request that has been cancelled.
 */
export interface CancelledRequestDetails { 
    /**
     * Comment made by the owner when cancelling the associated request.
     */
    comment?: string;
    owner?: OwnerDto;
    /**
     * Date comment was added by the owner when cancelling the associated request.
     */
    modified?: string;
}

