/**
 * Identity Security Cloud API - Access Requests
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Author of the comment
 */
export interface CommentDtoAuthor { 
    /**
     * The type of object
     */
    type?: CommentDtoAuthorTypeEnum;
    /**
     * The unique ID of the object
     */
    id?: string;
    /**
     * The display name of the object
     */
    name?: string;
}
export enum CommentDtoAuthorTypeEnum {
    Identity = 'IDENTITY'
};



