/**
 * Identity Security Cloud API - Access Requests
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestedItemDtoRef } from './requestedItemDtoRef';


export interface RequestedForDtoRef { 
    /**
     * The identity id the access is requested for. * `HUMAN` (default): the human identity id. * `MACHINE`: the machine identity id (hyphenated RFC-4122 UUID, not the correlated human identity). 
     */
    identityId: string;
    /**
     * Type of identity the access is requested for. * `HUMAN` (default) - standard human identity access request. * `MACHINE` - machine identity access request. When `MACHINE`, all entries in the request must also be `MACHINE` (mixed human and machine identities in one request are not supported), and only `ENTITLEMENT` items are allowed. 
     */
    identityType?: RequestedForDtoRefIdentityTypeEnum;
    /**
     * the details for the access items that are requested for the identity
     */
    requestedItems: Array<RequestedItemDtoRef>;
}
export enum RequestedForDtoRefIdentityTypeEnum {
    Human = 'HUMAN',
    Machine = 'MACHINE'
};



