/**
 * Identity Security Cloud API - Certifications
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityInsights } from './activityInsights';
import { ReviewableEntitlementAccountOwner } from './reviewableEntitlementAccountOwner';
import { DtoType } from './dtoType';


/**
 * Information about the status of the entitlement
 */
export interface ReviewableEntitlementAccount { 
    /**
     * The native identity for this account
     */
    nativeIdentity?: string;
    /**
     * Indicates whether this account is currently disabled
     */
    disabled?: boolean;
    /**
     * Indicates whether this account is currently locked
     */
    locked?: boolean;
    type?: DtoType;
    /**
     * The id associated with the account
     */
    id?: string | null;
    /**
     * The account name
     */
    name?: string | null;
    /**
     * When the account was created
     */
    created?: string | null;
    /**
     * When the account was last modified
     */
    modified?: string | null;
    activityInsights?: ActivityInsights;
    /**
     * Information about the account
     */
    description?: string | null;
    /**
     * The id associated with the machine Account Governance Group
     */
    governanceGroupId?: string | null;
    owner?: ReviewableEntitlementAccountOwner | null;
}



