/**
 * Identity Security Cloud API - Certifications
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdentityReferenceWithNameAndEmail } from './identityReferenceWithNameAndEmail';
import { ReviewableAccessProfile } from './reviewableAccessProfile';
import { ReviewableEntitlement } from './reviewableEntitlement';


export interface ReviewableRole { 
    /**
     * The id for the Role
     */
    id?: string;
    /**
     * The name of the Role
     */
    name?: string;
    /**
     * Information about the Role
     */
    description?: string;
    /**
     * Indicates if the entitlement is a privileged entitlement
     */
    privileged?: boolean;
    owner?: IdentityReferenceWithNameAndEmail | null;
    /**
     * Indicates whether the Role can be revoked or requested
     */
    revocable?: boolean;
    /**
     * The date when a user\'s access expires.
     */
    endDate?: string;
    /**
     * The list of Access Profiles associated with this Role
     */
    accessProfiles?: Array<ReviewableAccessProfile>;
    /**
     * The list of entitlements associated with this Role
     */
    entitlements?: Array<ReviewableEntitlement>;
}

