/**
 * Identity Security Cloud API - Certifications
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReviewRecommendation { 
    /**
     * The recommendation from IAI at the time of the decision. This field will be null if no recommendation was made.
     */
    recommendation?: string | null;
    /**
     * A list of reasons for the recommendation.
     */
    reasons?: Array<string>;
    /**
     * The time at which the recommendation was recorded.
     */
    timestamp?: string;
}

