/**
 * Identity Security Cloud API - Identities
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InviteIdentitiesRequest { 
    /**
     * The list of Identities IDs to invite - required when \'uninvited\' is false
     */
    ids?: Array<string> | null;
    /**
     * indicator (optional) to invite all unregistered identities in the system within a limit 1000. This parameter makes sense only when \'ids\' is empty.
     */
    uninvited?: boolean;
}

