/**
 * Identity Security Cloud API - Identities
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContextAttributeDto } from './contextAttributeDto';
import { BaseReferenceDto } from './baseReferenceDto';


export interface RoleMatchDto { 
    roleRef?: BaseReferenceDto;
    matchedAttributes?: Array<ContextAttributeDto>;
}

