/**
 * Identity Security Cloud API - Approvals
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Approval Approve Request
 */
export interface ApprovalApproveRequest { 
    /**
     * Additional attributes as key-value pairs that are not part of the standard schema but can be included for custom data.
     */
    additionalAttributes?: { [key: string]: string; };
    /**
     * Comment associated with the request.
     */
    comment?: string;
    /**
     * Optional field for ServiceNow Administrators to specify which member of a governance group to override/approve on behalf of.
     */
    overrideApproverID?: string;
}

