/**
 * Identity Security Cloud API - Approvals
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Timezone configuration for cron schedules.
 */
export interface ApprovalConfigCronTimezone { 
    /**
     * Timezone location for cron schedules.
     */
    location?: string;
    /**
     * Timezone offset for cron schedules.
     */
    offset?: string;
}

