/**
 * Identity Security Cloud API - IAI Common Access
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of access item.
 */
export enum CommonAccessType {

    AccessProfile = 'ACCESS_PROFILE',

    Role = 'ROLE'
}

