/**
 * Identity Security Cloud API - IAI Common Access
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommonAccessItemAccess } from './commonAccessItemAccess';
import { CommonAccessItemState } from './commonAccessItemState';


export interface CommonAccessItemRequest { 
    access?: CommonAccessItemAccess;
    status?: CommonAccessItemState;
}



