/**
 * Identity Security Cloud API - Machine Account Mappings
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Attibute Mapping Object
 */
export interface AttributeMappingsAllOfTransformDefinitionAttributesInputAttributes { 
    /**
     * The name of attribute
     */
    attributeName?: string;
    /**
     * Name of the Source
     */
    sourceName?: string;
    /**
     * ID of the Source
     */
    name?: string;
}

