/**
 * Identity Security Cloud API - Shared Signals Framework (SSF)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthorizationScheme } from './authorizationScheme';


/**
 * SSF transmitter discovery metadata per the SSF specification.
 */
export interface TransmitterMetadata { 
    /**
     * Version of the SSF specification supported.
     */
    spec_version?: string;
    /**
     * Base URL of the transmitter (issuer).
     */
    issuer?: string;
    /**
     * URL of the transmitter\'s JSON Web Key Set.
     */
    jwks_uri?: string;
    /**
     * Supported delivery methods (e.g. push URN).
     */
    delivery_methods_supported?: Array<string>;
    /**
     * Endpoint for stream configuration (create, read, update, replace, delete).
     */
    configuration_endpoint?: string;
    /**
     * Endpoint for reading and updating stream status.
     */
    status_endpoint?: string;
    /**
     * Endpoint for receiver verification.
     */
    verification_endpoint?: string;
    /**
     * Supported authorization schemes (e.g. OAuth2, Bearer).
     */
    authorization_schemes?: Array<AuthorizationScheme>;
}

