/**
 * Identity Security Cloud API - Machine Accounts
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateMachineAccountSubtypeV1Request { 
    /**
     * Technical name of the subtype.
     */
    technicalName: string;
    /**
     * Display name of the subtype.
     */
    displayName: string;
    /**
     * Description of the subtype.
     */
    description: string;
    /**
     * Type of the subtype.
     */
    type?: string;
}

