/**
 * Identity Security Cloud API - Machine Accounts
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Machine account async response containing the id of the started task.
 */
export interface MachineAccountsAsyncResult { 
    /**
     * ID of the task.
     */
    id: string;
}

