/**
 * Identity Security Cloud API - Machine Accounts
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Entro risk for this machine account. Present when Entro enrichment is enabled for the tenant. Null when no risk has been recorded. `score` stays null until a risk-engine projection exists. Read-only; written only by aggregation. This is separate from machine-identity SAF risk.
 */
export interface MachineAccountAllOfRisk { 
    /**
     * Risk score. Null for Entro-only severity.
     */
    score?: number | null;
    /**
     * Risk severity. A null stored severity can render as UNKNOWN when that behavior is enabled.
     */
    severity?: MachineAccountAllOfRiskSeverityEnum | null;
}
export enum MachineAccountAllOfRiskSeverityEnum {
    Unknown = 'UNKNOWN',
    Low = 'LOW',
    Medium = 'MEDIUM',
    High = 'HIGH',
    Critical = 'CRITICAL'
};



