/**
 * Identity Security Cloud API - OAuth Clients
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Access type of API Client indicating online or offline use
 */
export enum AccessType {

    Online = 'ONLINE',

    Offline = 'OFFLINE'
}

