/**
 * Identity Security Cloud API - Intelligence
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Intelmachineentityref } from './intelmachineentityref';
import { Intelblastradiussummary } from './intelblastradiussummary';


/**
 * Derived SOC triage signals for non-human identity risk assessment.
 */
export interface Intelmachinederived { 
    /**
     * Flags NHIs without a valid active owner for prioritization.
     */
    isOrphaned: boolean;
    /**
     * Humans who can invoke or access this NHI agent.
     */
    authorizedHumanIdentities: Array<Intelmachineentityref>;
    blastRadiusSummary: Intelblastradiussummary;
}

