/**
 * Identity Security Cloud API - Intelligence
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Typed id and name reference for owners, machine identities, and authorized humans.
 */
export interface Intelmachineentityref { 
    /**
     * Reference type label from upstream (for example IDENTITY or MACHINE_IDENTITY).
     */
    type: string;
    /**
     * Referenced object identifier.
     */
    id: string;
    /**
     * Display name for the referenced identity or entity.
     */
    name: string;
    /**
     * Email for authorized human holders when available upstream.
     */
    email?: string;
}

