/**
 * Identity Security Cloud API - Intelligence
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntelRareAccessSlice } from './intelRareAccessSlice';


/**
 * Outlier slices embedded in the aggregate identity response.
 */
export interface IntelOutliersSlice { 
    /**
     * First page of rare access items for the identity.
     */
    rareAccess: IntelRareAccessSlice;
}

