/**
 * Identity Security Cloud API - Intelligence
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorMessageDto } from './errorMessageDto';


export interface IntelIdentityNotFoundBody { 
    /**
     * Constant detail code indicating that no identity matched the supplied filter.
     */
    detailCode: IntelIdentityNotFoundBodyDetailCodeEnum;
    /**
     * Unique tracking id for the error.
     */
    trackingId?: string;
    /**
     * Generic localized reason for error
     */
    messages?: Array<ErrorMessageDto>;
    /**
     * Plain-text descriptive reasons to provide additional detail to the text provided in the messages field
     */
    causes?: Array<ErrorMessageDto>;
}
export enum IntelIdentityNotFoundBodyDetailCodeEnum {
    IdcIdentityNotFound = 'IDC_IDENTITY_NOT_FOUND'
};



