/**
 * Identity Security Cloud API - Intelligence
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Source metadata associated with the privileged access item when present.
 */
export interface IntelPrivilegedAccessItemWireSource { 
    /**
     * Human-readable source name for the privileged access item.
     */
    name?: string;
    /**
     * Source identifier for the privileged access item.
     */
    id?: string;
}

