/**
 * Identity Security Cloud API - Intelligence
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntelPrivilegedAccessItemWireSource } from './intelPrivilegedAccessItemWireSource';
import { Intelprivilegelevel } from './intelprivilegelevel';


export interface IntelPrivilegedAccessItemWire { 
    /**
     * True when this item is classified as privileged access for the identity.
     */
    privileged: boolean;
    privilegeLevel?: Intelprivilegelevel;
    /**
     * Identifier of the privileged access item.
     */
    id: string;
    /**
     * Type of privileged access object.
     */
    type: string;
    /**
     * Display label for the privileged access item in administrative experiences.
     */
    displayName?: string;
    /**
     * Technical name of the privileged access item.
     */
    name?: string;
    source?: IntelPrivilegedAccessItemWireSource;
    /**
     * Source attribute name that carries the privileged value when applicable.
     */
    attribute?: string;
    /**
     * Privileged value on the source attribute when applicable.
     */
    value?: string;
}

