/**
 * Identity Security Cloud API - Intelligence
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseactioncreaterequestOneOf1 { 
    actionType?: ResponseactioncreaterequestOneOf1ActionTypeEnum;
}
export enum ResponseactioncreaterequestOneOf1ActionTypeEnum {
    DisableAccount = 'DISABLE_ACCOUNT'
};



