/**
 * Identity Security Cloud API - Sources
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DependantAppConnectionsAccountSourcePasswordPoliciesInner } from './dependantAppConnectionsAccountSourcePasswordPoliciesInner';


/**
 * The Account Source of the connected Application
 */
export interface DependantAppConnectionsAccountSource { 
    /**
     * Use this Account Source for password management
     */
    useForPasswordManagement?: boolean;
    /**
     * A list of Password Policies for this Account Source
     */
    passwordPolicies?: Array<DependantAppConnectionsAccountSourcePasswordPoliciesInner>;
}

