/**
 * Identity Security Cloud API - Sources
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DependantConnectionsMissingDto { 
    /**
     * The type of dependency type that is missing in the SourceConnections
     */
    dependencyType?: DependantConnectionsMissingDtoDependencyTypeEnum;
    /**
     * The reason why this dependency is missing
     */
    reason?: string;
}
export enum DependantConnectionsMissingDtoDependencyTypeEnum {
    IdentityProfiles = 'identityProfiles',
    CredentialProfiles = 'credentialProfiles',
    MappingProfiles = 'mappingProfiles',
    SourceAttributes = 'sourceAttributes',
    DependantCustomTransforms = 'dependantCustomTransforms',
    DependantApps = 'dependantApps'
};



