/**
 * Identity Security Cloud API - Sources
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImportAccountsV1Request { 
    /**
     * The CSV file containing the source accounts to aggregate.
     */
    file?: Blob;
    /**
     * Use this flag to reprocess every account whether or not the data has changed.
     */
    disableOptimization?: string;
}

