/**
 * Identity Security Cloud API - Sources
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoadAccountsTaskTaskMessagesInner { 
    /**
     * Type of the message.
     */
    type?: LoadAccountsTaskTaskMessagesInnerTypeEnum;
    /**
     * Flag whether message is an error.
     */
    error?: boolean;
    /**
     * Flag whether message is a warning.
     */
    warning?: boolean;
    /**
     * Message string identifier.
     */
    key?: string;
    /**
     * Message context with the locale based language.
     */
    localizedText?: string;
}
export enum LoadAccountsTaskTaskMessagesInnerTypeEnum {
    Info = 'INFO',
    Warn = 'WARN',
    Error = 'ERROR'
};



