/**
 * Identity Security Cloud API - Sources
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoadEntitlementTaskReturnsInner { 
    /**
     * The display label for the return value
     */
    displayLabel?: string;
    /**
     * The attribute name for the return value
     */
    attributeName?: string;
}

