/**
 * Identity Security Cloud API - Sources
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoadUncorrelatedAccountsTaskTask } from './loadUncorrelatedAccountsTaskTask';


export interface LoadUncorrelatedAccountsTask { 
    /**
     * The status of the result
     */
    success?: boolean;
    task?: LoadUncorrelatedAccountsTaskTask;
}

