/**
 * Identity Security Cloud API - Sources
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Extra attributes map(dictionary) for the task.
 */
export interface LoadUncorrelatedAccountsTaskTaskAttributes { 
    /**
     * The id of qpoc job
     */
    qpocJobId?: string;
    /**
     * the task start delay value
     */
    taskStartDelay?: any | null;
}

