/**
 * Identity Security Cloud API - Sources
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceObject } from './resourceObject';


/**
 * Response model for peek resource objects from source connectors.
 */
export interface ResourceObjectsResponse { 
    /**
     * ID of the source
     */
    readonly id?: string;
    /**
     * Name of the source
     */
    readonly name?: string;
    /**
     * The number of objects that were fetched by the connector.
     */
    readonly objectCount?: number;
    /**
     * The number of milliseconds spent on the entire request.
     */
    readonly elapsedMillis?: number;
    /**
     * Fetched objects from the source connector.
     */
    readonly resourceObjects?: Array<ResourceObject>;
}

