/**
 * Identity Security Cloud API - Sources
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Simplified resource reference associated with a source dataset.
 */
export interface SourceDatasetResourceReference { 
    /**
     * Resource identifier.
     */
    id?: string;
    /**
     * Display name of the resource.
     */
    name?: string;
    /**
     * Resource type from source schema config.
     */
    type?: string;
}

