/**
 * Identity Security Cloud API - Sources
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntitlementRevocationRequestConfig } from './entitlementRevocationRequestConfig';
import { EntitlementAccessRequestConfig } from './entitlementAccessRequestConfig';


/**
 * Entitlement Request Configuration
 */
export interface SourceEntitlementRequestConfig { 
    accessRequestConfig?: EntitlementAccessRequestConfig;
    revocationRequestConfig?: EntitlementRevocationRequestConfig;
}

