/**
 * Identity Security Cloud API - IAI Role Mining
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityCreatedByDTO } from './entityCreatedByDTO';


/**
 * The potential role created by details
 */
/**
 * @type RoleMiningPotentialRoleSummaryCreatedBy
 * The potential role created by details
 * @export
 */
export type RoleMiningPotentialRoleSummaryCreatedBy = EntityCreatedByDTO | string;

