/**
 * Identity Security Cloud API - Public Identities Config
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Used to map an attribute key for an Identity to its display name.
 */
export interface PublicIdentityAttributeConfig { 
    /**
     * The attribute key
     */
    key?: string;
    /**
     * The attribute display name
     */
    name?: string;
}

