/**
 * Identity Security Cloud API - Apps
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SourceAppAccountSource } from './sourceAppAccountSource';
import { BaseReferenceDto } from './baseReferenceDto';


export interface SourceAppPatchDto { 
    /**
     * The source app id
     */
    id?: string;
    /**
     * The deprecated source app id
     */
    cloudAppId?: string;
    /**
     * The source app name
     */
    name?: string;
    /**
     * Time when the source app was created
     */
    created?: string;
    /**
     * Time when the source app was last modified
     */
    modified?: string;
    /**
     * True if the source app is enabled
     */
    enabled?: boolean;
    /**
     * True if the app allows access request
     */
    provisionRequestEnabled?: boolean;
    /**
     * The description of the source app
     */
    description?: string;
    /**
     * True if the source app match all accounts
     */
    matchAllAccounts?: boolean;
    /**
     * True if the app is visible in the request center
     */
    appCenterEnabled?: boolean;
    /**
     * List of IDs of access profiles
     */
    accessProfiles?: Array<string> | null;
    accountSource?: SourceAppAccountSource | null;
    /**
     * The owner of source app
     */
    owner?: BaseReferenceDto | null;
}

