/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileAttributeRuleIdNERM } from './profileAttributeRuleId';
import { ProfileAttributeRuleStringNERM } from './profileAttributeRuleString';
import { RiskRuleNERM } from './riskRule';
import { ProfileTypeRuleNERM } from './profileTypeRule';
import { ProfileAttributeRuleDateNERM } from './profileAttributeRuleDate';
import { ProfileStatusRuleNERM } from './profileStatusRule';


export interface AdvancedSearchConditionRulesAttributesInnerNERM { 
    readonly id?: string;
    readonly uid?: string;
    type: AdvancedSearchConditionRulesAttributesInnerNERMTypeNerm;
    comparison_operator: AdvancedSearchConditionRulesAttributesInnerNERMComparisonOperatorNerm;
    value: string;
    condition_object_type: AdvancedSearchConditionRulesAttributesInnerNERMConditionObjectTypeNerm;
    condition_object_id: string;
    secondary_attribute_type?: AdvancedSearchConditionRulesAttributesInnerNERMSecondaryAttributeTypeNerm;
    secondary_attribute_id?: string;
    secondary_value: AdvancedSearchConditionRulesAttributesInnerNERMSecondaryValueNerm;
    tertiary_value?: string;
}
export enum AdvancedSearchConditionRulesAttributesInnerNERMTypeNerm {
    ProfileTypeRule = 'ProfileTypeRule',
    ProfileStatusRule = 'ProfileStatusRule',
    ProfileAttributeRule = 'ProfileAttributeRule',
    RiskRule = 'RiskRule'
};
export enum AdvancedSearchConditionRulesAttributesInnerNERMComparisonOperatorNerm {
    DoubleEqual = '==',
    GreaterThan = '>',
    LessThan = '<'
};
export enum AdvancedSearchConditionRulesAttributesInnerNERMConditionObjectTypeNerm {
    ProfileSelectAttribute = 'ProfileSelectAttribute',
    ProfileSearchAttribute = 'ProfileSearchAttribute',
    OwnerSelectAttribute = 'OwnerSelectAttribute',
    OwnerSearchAttribute = 'OwnerSearchAttribute',
    ContributorSelectAttribute = 'ContributorSelectAttribute',
    ContributorSearchAttribute = 'ContributorSearchAttribute'
};
export enum AdvancedSearchConditionRulesAttributesInnerNERMSecondaryAttributeTypeNerm {
    DateAttribute = 'DateAttribute'
};
export enum AdvancedSearchConditionRulesAttributesInnerNERMSecondaryValueNerm {
    OverallRisk = 'OverallRisk'
};



