/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowActionPerformers1NERM } from './workflowActionPerformers1';


export interface CreateWorkflowActionPerformerRequestNERM { 
    workflow_action_performers?: WorkflowActionPerformers1NERM;
}

