/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileTypeRolesNERM } from './profileTypeRoles';


export interface CreateProfileTypeRole200ResponseNERM { 
    profile_type_roles?: ProfileTypeRolesNERM;
}

