/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DelegationNERM { 
    /**
     * The id of the delegation
     */
    id?: string;
    /**
     * The id of the delegator user
     */
    delegator_id?: object;
    /**
     * The id of the delegate user
     */
    delegate_id?: object;
    /**
     * The expiration date of the delegation
     */
    expiration?: string;
    /**
     * Indicates if the delegation is expired
     */
    expired?: boolean;
    /**
     * The date-time the record created.
     */
    readonly created_at?: string;
    /**
     * The date-time the record was last updated.
     */
    readonly updated_at?: string;
}

