/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Form1NERM { 
    /**
     * The user-specified identifier of the form
     */
    uid?: string;
    /**
     * The description of the form
     */
    description?: string;
    /**
     * The name of the form
     */
    name?: string;
    /**
     * Determines whether the form is archived
     */
    archived?: boolean;
}

