/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetProfileTypeAttributesSortParameterNERM { 
    attr?: string;
    order?: GetProfileTypeAttributesSortParameterNERMOrderNerm;
}
export enum GetProfileTypeAttributesSortParameterNERMOrderNerm {
    Asc = 'asc',
    Desc = 'desc'
};



