/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvitationActionWorkflowActionEmailAttributesNERM { 
    /**
     * the id.
     */
    id?: string;
    /**
     * the id of the workflow action.
     */
    workflow_action_id?: string;
    /**
     * the id of the email.
     */
    email_id?: string;
    /**
     * the type of email.
     */
    type?: InvitationActionWorkflowActionEmailAttributesNERMTypeNerm;
}
export enum InvitationActionWorkflowActionEmailAttributesNERMTypeNerm {
    StandardEmail = 'StandardEmail',
    PerformerNotificationEmail = 'PerformerNotificationEmail',
    ApprovalEmail = 'ApprovalEmail',
    RejectionEmail = 'RejectionEmail'
};



