/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvitationActionConfigurationAttributesNERM { 
    /**
     * the id.
     */
    id?: string;
    /**
     * If the invitation action should pause the parent workflow to wait for completion.
     */
    wait_for_completion?: boolean;
    /**
     * If the invitation action should return a profile.
     */
    return_profile?: boolean;
    /**
     * the id of the portal.
     */
    portal_id?: string;
    /**
     * the id of the registration workflow.
     */
    registration_workflow_id?: string;
    /**
     * the id of the email attribute.
     */
    email_attribute_id?: string;
    /**
     * If the action should validate against completed registrations by email address.
     */
    validate_completed_registration?: boolean;
    /**
     * If the action should validate against open registrations by email address.
     */
    validate_open_registration?: boolean;
}

