/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PageContentTranslationNERM { 
    /**
     * The id of the page content
     */
    readonly id?: string;
    /**
     * The user-specified identifier for the record
     */
    uid?: string;
    /**
     * The language locale this translation contains.
     */
    locale?: string;
    /**
     * The translated string to present in the user interface.
     */
    value?: string;
    /**
     * The date-time the record created.
     */
    readonly created_at?: string;
    /**
     * The date-time the record was last updated.
     */
    readonly updated_at?: string;
}

