/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProfileStatusRuleNERM { 
    readonly id?: string;
    readonly uid?: string;
    type: ProfileStatusRuleNERMTypeNerm;
    comparison_operator?: ProfileStatusRuleNERMComparisonOperatorNerm;
    value?: ProfileStatusRuleNERMValueNerm;
}
export enum ProfileStatusRuleNERMTypeNerm {
    ProfileStatusRule = 'ProfileStatusRule'
};
export enum ProfileStatusRuleNERMComparisonOperatorNerm {
    DoubleEqual = '==',
    NotEqual = '!='
};
export enum ProfileStatusRuleNERMValueNerm {
    Active = 'Active',
    Inactive = 'Inactive',
    LeaveOfAbsence = 'Leave of absence',
    Terminated = 'Terminated'
};



