/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProfileTypeAttributeNERM { 
    /**
     * ID of ne attribute
     */
    readonly id?: string;
    /**
     * Ne attribute\'s uid
     */
    readonly uid?: string;
    /**
     * Ne attribute\'s label
     */
    readonly label: string;
    /**
     * synced_attribute ID if there is one
     */
    synced?: string;
}

