/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReviewActionNERM { 
    /**
     * The workflow the workflow action belongs to.
     */
    workflow_id: string;
    /**
     * The description of the workflow action.
     */
    description: string;
    /**
     * The page the workflow action should render.
     */
    page_id?: string;
    /**
     * If the workflow action is archived or not.
     */
    archived?: boolean;
    /**
     * If the workflow action requires a comment or not.
     */
    requires_comment?: boolean;
}

