/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleProfileNERM } from './roleProfile';


export interface RoleProfilesNERM { 
    role_profiles?: Array<RoleProfileNERM>;
}

