/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditEventNERM } from './auditEvent';


export interface Search200ResponseNERM { 
    audit_events?: Array<AuditEventNERM>;
}

