/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileTypeNERM } from './profileType';


export interface SubmitProfileType200ResponseNERM { 
    profile_type?: ProfileTypeNERM;
}

