/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role1NERM } from './role1';


export interface SubmitRolesRequestNERM { 
    roles?: Array<Role1NERM>;
}

