/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributeOption1NERM } from './attributeOption1';


export interface SubmitAttributeOptionsRequestNERM { 
    ne_attribute_options?: Array<AttributeOption1NERM>;
}

