/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdvancedSearchNERM } from './advancedSearch';


export interface SubmitAdvancedSearch200ResponseNERM { 
    advanced_search?: AdvancedSearchNERM;
}

