/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateProfileRequestProfileNERM } from './updateProfileRequestProfile';


export interface UpdateProfileRequestNERM { 
    profile: UpdateProfileRequestProfileNERM;
}

