/**
 * NERM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Form1NERM } from './form1';


export interface UpdateFormByIdRequestNERM { 
    role?: Form1NERM;
}

