/**
 * Identity Security Cloud API - Managed Clusters
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClusterManualUpgradeJobsInner } from './clusterManualUpgradeJobsInner';


/**
 * Manual Upgrade Job Response
 */
export interface ClusterManualUpgrade { 
    /**
     * List of job objects for the upgrade request.
     */
    jobs?: Array<ClusterManualUpgradeJobsInner>;
}

