/**
 * Identity Security Cloud API - Managed Clusters
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Defines the encryption settings for a managed cluster, including the format used for storing and processing encrypted data.
 */
export interface ManagedClusterEncryptionConfig { 
    /**
     * Specifies the format used for encrypted data, such as secrets. The format determines how the encrypted data is structured and processed.
     */
    format?: ManagedClusterEncryptionConfigFormatEnum;
}
export enum ManagedClusterEncryptionConfigFormatEnum {
    V2 = 'V2',
    V3 = 'V3'
};



