/**
 * Identity Security Cloud API - Search
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enum representing the currently supported indices. Additional values may be added in the future without notice.
 */
export enum Index {

    Accessprofiles = 'accessprofiles',

    Accountactivities = 'accountactivities',

    Entitlements = 'entitlements',

    Events = 'events',

    Identities = 'identities',

    Roles = 'roles',

    Star = '*'
}

