/**
 * Identity Security Cloud API - Certification Summaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoType } from './dtoType';


export interface AccessSummaryAccess { 
    type?: DtoType;
    /**
     * The ID of the item being certified
     */
    id?: string;
    /**
     * The name of the item being certified
     */
    name?: string;
}



