/**
 * Identity Security Cloud API - Machine Identity Lifecycle Actions
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LifecycleCommentAuthorReference { 
    /**
     * Author category for the comment.
     */
    type?: LifecycleCommentAuthorReferenceTypeEnum;
    /**
     * Identifier of the comment author.
     */
    id?: string;
    /**
     * Display name of the comment author.
     */
    name?: string;
}
export enum LifecycleCommentAuthorReferenceTypeEnum {
    Identity = 'IDENTITY',
    Workgroup = 'WORKGROUP',
    ApiToken = 'API_TOKEN',
    System = 'SYSTEM'
};



