/**
 * Generic Identity Security Cloud V2025 API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * @type GenericResponse
 * @export
 */
export type GenericResponse = Array<{ [key: string]: any; }> | { [key: string]: any; };

