/**
 * Identity Security Cloud API - Machine Identity Lifecycle Actions
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { CancelLifecycleActionRequest } from '../model/cancelLifecycleActionRequest';
// @ts-ignore
import { CancelLifecycleActionResponse } from '../model/cancelLifecycleActionResponse';
// @ts-ignore
import { ErrorResponseDto } from '../model/errorResponseDto';
// @ts-ignore
import { LifecycleActionRequest } from '../model/lifecycleActionRequest';
// @ts-ignore
import { LifecycleActionSubmitRequest } from '../model/lifecycleActionSubmitRequest';
// @ts-ignore
import { LifecycleActionSubmitResponse } from '../model/lifecycleActionSubmitResponse';
// @ts-ignore
import { SubmitMachineIdentityLifecycleActionV1401Response } from '../model/submitMachineIdentityLifecycleActionV1401Response';
// @ts-ignore
import { SubmitMachineIdentityLifecycleActionV1429Response } from '../model/submitMachineIdentityLifecycleActionV1429Response';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';


export interface CancelMachineIdentityLifecycleActionV1RequestParams {
    /** Lifecycle request identifier. */
    requestId: string;
    /** Use this header to enable this experimental API. */
    xSailPointExperimental?: string;
    cancelLifecycleActionRequest?: CancelLifecycleActionRequest;
}

export interface GetMachineIdentityLifecycleActionV1RequestParams {
    /** Lifecycle request identifier. */
    requestId: string;
    /** Use this header to enable this experimental API. */
    xSailPointExperimental?: string;
}

export interface ListMachineIdentityLifecycleActionsV1RequestParams {
    /** Filter results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#filtering-results)  Filtering is supported for the following fields and operators:  **resourceType**: *eq, in*  **operationType**: *eq, in*  **status**: *eq, in*  **completed**: *eq*  **targetId**: *eq*  **targetName**: *eq, sw*  **sourceId**: *eq*  **created**: *gt, ge, lt, le* */
    filters?: string;
    /** Sort results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#sorting-results)  Sorting is supported for the following fields: **created, modified, status**  Default sort is **-created** (newest first). */
    sorters?: string;
    /** Max number of results to return. When omitted, the default limit is 50. The maximum allowed limit is 250.  See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information. */
    limit?: number;
    /** Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information. */
    offset?: number;
    /** If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.  Since requesting a total count can have a performance impact, it is recommended not to send **count&#x3D;true** if that value will not be used.  See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information. */
    count?: boolean;
    /** Use this header to enable this experimental API. */
    xSailPointExperimental?: string;
}

export interface SubmitMachineIdentityLifecycleActionV1RequestParams {
    /** Machine identity ID. */
    id: string;
    lifecycleActionSubmitRequest: LifecycleActionSubmitRequest;
    /** Use this header to enable this experimental API. */
    xSailPointExperimental?: string;
}


@Injectable({
  providedIn: 'root'
})
export class MachineIdentityLifecycleActionsService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Cancel lifecycle action
     * Attempts to cancel a lifecycle request before provisioning starts.  The path &#x60;requestId&#x60; is authoritative for lookup and authorization. The request body is optional and may carry cancel metadata such as &#x60;comment&#x60;. Any &#x60;requestId&#x60; value in the body is ignored.  Workflow cancel signaling is attempted before the request is persisted as &#x60;CANCELING&#x60;. If signaling fails, the service returns **503** (&#x60;DOWNSTREAM_SERVICE_UNAVAILABLE&#x60;, cause &#x60;workflow-signal-failed&#x60;) and the lifecycle request status is unchanged.  Invalid cancel states are returned as **400** (&#x60;INVALID_REQUEST_IN_CURRENT_STATE&#x60; variants).  Cancel authorization matches https://developer.sailpoint.com/docs/api/get-machine-identity-lifecycle-action-v-1: the original submitter is always allowed; otherwise callers must have the &#x60;idn:machine-identity-lifecycle-action:manage&#x60; scope **and** target role-context access.  **403 Forbidden**  - &#x60;FORBIDDEN.lifecycle-request-access-denied&#x60; - caller is not the submitter and lacks both the   &#x60;idn:machine-identity-lifecycle-action:manage&#x60; scope and target role-context. - &#x60;FORBIDDEN.unsupported-type&#x60; - the persisted lifecycle row is not scoped to &#x60;AI_AGENT&#x60;.  **404 Not Found**  - &#x60;NOT_FOUND.detailed&#x60; - unknown &#x60;requestId&#x60;, or persisted &#x60;targetType&#x60;/target-identity subtype   mismatch. 
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cancelMachineIdentityLifecycleActionV1(requestParameters: CancelMachineIdentityLifecycleActionV1RequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<CancelLifecycleActionResponse>;
    public cancelMachineIdentityLifecycleActionV1(requestParameters: CancelMachineIdentityLifecycleActionV1RequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<CancelLifecycleActionResponse>>;
    public cancelMachineIdentityLifecycleActionV1(requestParameters: CancelMachineIdentityLifecycleActionV1RequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<CancelLifecycleActionResponse>>;
    public cancelMachineIdentityLifecycleActionV1(requestParameters: CancelMachineIdentityLifecycleActionV1RequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const requestId = requestParameters?.requestId;
        if (requestId === null || requestId === undefined) {
            throw new Error('Required parameter requestId was null or undefined when calling cancelMachineIdentityLifecycleActionV1.');
        }
        const xSailPointExperimental = requestParameters?.xSailPointExperimental;
        const cancelLifecycleActionRequest = requestParameters?.cancelLifecycleActionRequest;

        let localVarHeaders = this.defaultHeaders;
        if (xSailPointExperimental !== undefined && xSailPointExperimental !== null) {
            localVarHeaders = localVarHeaders.set('X-SailPoint-Experimental', String(xSailPointExperimental));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/machine-identities/v1/lifecycle-actions/${this.configuration.encodeParam({name: "requestId", value: requestId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}/cancel`;
        return this.httpClient.request<CancelLifecycleActionResponse>('post', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: cancelLifecycleActionRequest,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get lifecycle action by requestId
     * Returns one lifecycle request snapshot by &#x60;requestId&#x60;. Used for request-level inspection, including cancel acceptance and subsequent status changes.  The original requester is always allowed to read their request. Otherwise, callers must have the &#x60;idn:machine-identity-lifecycle-action:manage&#x60; scope **and** role-context access to the target machine identity (organization admin, source admin, scoped source sub-admin, or effective owner).  **403 Forbidden**  - &#x60;FORBIDDEN.lifecycle-request-access-denied&#x60; - caller is not the submitter and lacks both the   &#x60;idn:machine-identity-lifecycle-action:manage&#x60; scope and target role-context (response includes &#x60;requestId&#x60; as a parameter). - &#x60;FORBIDDEN.unsupported-type&#x60; - the persisted lifecycle row is not scoped to &#x60;AI_AGENT&#x60;   (&#x60;targetType&#x60; on read-by-request-id paths).  **404 Not Found**  - &#x60;NOT_FOUND.detailed&#x60; - unknown &#x60;requestId&#x60;, or persisted &#x60;targetType&#x60; does not match the   target machine identity\&#39;s subtype-to-resource-type mapping. 
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMachineIdentityLifecycleActionV1(requestParameters: GetMachineIdentityLifecycleActionV1RequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LifecycleActionRequest>;
    public getMachineIdentityLifecycleActionV1(requestParameters: GetMachineIdentityLifecycleActionV1RequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LifecycleActionRequest>>;
    public getMachineIdentityLifecycleActionV1(requestParameters: GetMachineIdentityLifecycleActionV1RequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LifecycleActionRequest>>;
    public getMachineIdentityLifecycleActionV1(requestParameters: GetMachineIdentityLifecycleActionV1RequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const requestId = requestParameters?.requestId;
        if (requestId === null || requestId === undefined) {
            throw new Error('Required parameter requestId was null or undefined when calling getMachineIdentityLifecycleActionV1.');
        }
        const xSailPointExperimental = requestParameters?.xSailPointExperimental;

        let localVarHeaders = this.defaultHeaders;
        if (xSailPointExperimental !== undefined && xSailPointExperimental !== null) {
            localVarHeaders = localVarHeaders.set('X-SailPoint-Experimental', String(xSailPointExperimental));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/machine-identities/v1/lifecycle-actions/${this.configuration.encodeParam({name: "requestId", value: requestId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;
        return this.httpClient.request<LifecycleActionRequest>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List lifecycle actions
     * Lists lifecycle requests visible to the requester identity in the current request context.  Results are automatically scoped to the calling identity. If requester identity context is missing, an empty list is returned.  When &#x60;limit&#x60; is omitted, this endpoint applies a default limit of 50. 
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listMachineIdentityLifecycleActionsV1(requestParameters?: ListMachineIdentityLifecycleActionsV1RequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<LifecycleActionRequest>>;
    public listMachineIdentityLifecycleActionsV1(requestParameters?: ListMachineIdentityLifecycleActionsV1RequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<LifecycleActionRequest>>>;
    public listMachineIdentityLifecycleActionsV1(requestParameters?: ListMachineIdentityLifecycleActionsV1RequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<LifecycleActionRequest>>>;
    public listMachineIdentityLifecycleActionsV1(requestParameters?: ListMachineIdentityLifecycleActionsV1RequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const filters = requestParameters?.filters;
        const sorters = requestParameters?.sorters;
        const limit = requestParameters?.limit;
        const offset = requestParameters?.offset;
        const count = requestParameters?.count;
        const xSailPointExperimental = requestParameters?.xSailPointExperimental;

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>filters, 'filters');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sorters, 'sorters');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>limit, 'limit');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>offset, 'offset');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>count, 'count');

        let localVarHeaders = this.defaultHeaders;
        if (xSailPointExperimental !== undefined && xSailPointExperimental !== null) {
            localVarHeaders = localVarHeaders.set('X-SailPoint-Experimental', String(xSailPointExperimental));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/machine-identities/v1/lifecycle-actions`;
        return this.httpClient.request<Array<LifecycleActionRequest>>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Submit machine identity lifecycle action
     * Creates a lifecycle request for the target machine identity and returns the created lifecycle snapshot.  The response includes the generated &#x60;requestId&#x60;, which is used by https://developer.sailpoint.com/docs/api/list-machine-identity-lifecycle-actions-v-1, https://developer.sailpoint.com/docs/api/get-machine-identity-lifecycle-action-v-1, and https://developer.sailpoint.com/docs/api/cancel-machine-identity-lifecycle-action-v-1  Authorization is enforced in the service layer. Callers must have the &#x60;idn:machine-identity-lifecycle-action:manage&#x60; scope or role-context access to the target machine identity (organization admin, source admin, scoped source sub-admin, or effective owner).  Supported actions are &#x60;DEACTIVATE&#x60;, &#x60;ACTIVATE&#x60;. 
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public submitMachineIdentityLifecycleActionV1(requestParameters: SubmitMachineIdentityLifecycleActionV1RequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LifecycleActionSubmitResponse>;
    public submitMachineIdentityLifecycleActionV1(requestParameters: SubmitMachineIdentityLifecycleActionV1RequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LifecycleActionSubmitResponse>>;
    public submitMachineIdentityLifecycleActionV1(requestParameters: SubmitMachineIdentityLifecycleActionV1RequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LifecycleActionSubmitResponse>>;
    public submitMachineIdentityLifecycleActionV1(requestParameters: SubmitMachineIdentityLifecycleActionV1RequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling submitMachineIdentityLifecycleActionV1.');
        }
        const lifecycleActionSubmitRequest = requestParameters?.lifecycleActionSubmitRequest;
        if (lifecycleActionSubmitRequest === null || lifecycleActionSubmitRequest === undefined) {
            throw new Error('Required parameter lifecycleActionSubmitRequest was null or undefined when calling submitMachineIdentityLifecycleActionV1.');
        }
        const xSailPointExperimental = requestParameters?.xSailPointExperimental;

        let localVarHeaders = this.defaultHeaders;
        if (xSailPointExperimental !== undefined && xSailPointExperimental !== null) {
            localVarHeaders = localVarHeaders.set('X-SailPoint-Experimental', String(xSailPointExperimental));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/machine-identities/v1/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}/lifecycle-actions`;
        return this.httpClient.request<LifecycleActionSubmitResponse>('post', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: lifecycleActionSubmitRequest,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
