/**
 * Identity Security Cloud API - Non-Employee Lifecycle Management
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NonEmployeeIdnUserRequest } from './nonEmployeeIdnUserRequest';


export interface NonEmployeeSourceRequestBody { 
    /**
     * Name of non-employee source.
     */
    name: string;
    /**
     * Description of non-employee source.
     */
    description: string;
    owner: NonEmployeeIdnUserRequest;
    /**
     * The ID for the management workgroup that contains source sub-admins
     */
    managementWorkgroup?: string;
    /**
     * List of approvers.
     */
    approvers?: Array<NonEmployeeIdnUserRequest>;
    /**
     * List of account managers.
     */
    accountManagers?: Array<NonEmployeeIdnUserRequest>;
}

