/**
 * Identity Security Cloud API - Machine Account Classify
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SendClassifyMachineAccountV1200Response { 
    /**
     * Indicates if account is classified as machine
     */
    isMachine?: boolean;
}

