/**
 * Identity Security Cloud API - Service Desk Integration
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Configuration of maximum number of days and interval for checking Service Desk integration queue status.
 */
export interface QueuedCheckConfigDetails { 
    /**
     * Interval in minutes between status checks
     */
    provisioningStatusCheckIntervalMinutes: string;
    /**
     * Maximum number of days to check
     */
    provisioningMaxStatusCheckDays: string;
}

