/**
 * Identity Security Cloud API - Notifications
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The notification delivery medium.
 */
export enum TemplateMediumDto {

    Email = 'EMAIL',

    Slack = 'SLACK',

    Teams = 'TEAMS'
}

