/**
 * Identity Security Cloud API - Global Tenant Security Settings
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetAuthOrgNetworkConfigV1401Response { 
    /**
     * A message describing the error
     */
    error?: any | null;
}

