/**
 * Identity Security Cloud API - Global Tenant Security Settings
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JITConfiguration } from './jITConfiguration';


export interface IdpDetails { 
    /**
     * Federation protocol role
     */
    role?: IdpDetailsRoleEnum;
    /**
     * An entity ID is a globally unique name for a SAML entity, either an Identity Provider (IDP) or a Service Provider (SP).
     */
    entityId?: string;
    /**
     * Defines the binding used for the SAML flow. Used with IDP configurations.
     */
    binding?: string;
    /**
     * Specifies the SAML authentication method to use. Used with IDP configurations.
     */
    authnContext?: string;
    /**
     * The IDP logout URL. Used with IDP configurations.
     */
    logoutUrl?: string;
    /**
     * Determines if the configured AuthnContext should be used or the default. Used with IDP configurations.
     */
    includeAuthnContext?: boolean;
    /**
     * The name id format to use. Used with IDP configurations.
     */
    nameId?: string;
    jitConfiguration?: JITConfiguration;
    /**
     * The Base64-encoded certificate used by the IDP. Used with IDP configurations.
     */
    cert?: string;
    /**
     * The IDP POST URL, used with IDP HTTP-POST bindings for IDP-initiated logins. Used with IDP configurations.
     */
    loginUrlPost?: string;
    /**
     * The IDP Redirect URL. Used with IDP configurations.
     */
    loginUrlRedirect?: string;
    /**
     * Return the saml Id for the given user, based on the IDN as SP settings of the org. Used with IDP configurations.
     */
    mappingAttribute: string;
    /**
     * The expiration date extracted from the certificate.
     */
    certificateExpirationDate?: string;
    /**
     * The name extracted from the certificate.
     */
    certificateName?: string;
}
export enum IdpDetailsRoleEnum {
    SamlIdp = 'SAML_IDP',
    SamlSp = 'SAML_SP'
};



