/**
 * Identity Security Cloud API - Global Tenant Security Settings
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JITConfiguration { 
    /**
     * The indicator for just-in-time provisioning enabled
     */
    enabled?: boolean;
    /**
     * the sourceId that mapped to just-in-time provisioning configuration
     */
    sourceId?: string;
    /**
     * A mapping of identity profile attribute names to SAML assertion attribute names
     */
    sourceAttributeMappings?: { [key: string]: string; };
}

