/**
 * Identity Security Cloud API - Global Tenant Security Settings
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceProviderConfigurationFederationProtocolDetailsInner } from './serviceProviderConfigurationFederationProtocolDetailsInner';


/**
 * Represents the IdentityNow as Service Provider Configuration allowing customers to log into IDN via an Identity Provider
 */
export interface ServiceProviderConfiguration { 
    /**
     * This determines whether or not the SAML authentication flow is enabled for an org
     */
    enabled?: boolean;
    /**
     * This allows basic login with the parameter prompt=true. This is often toggled on when debugging SAML authentication setup. When false, only org admins with MFA-enabled can bypass the IDP.
     */
    bypassIdp?: boolean;
    /**
     * This indicates whether or not the SAML configuration is valid.
     */
    samlConfigurationValid?: boolean;
    /**
     * A list of the abstract implementations of the Federation Protocol details. Typically, this will include on SpDetails object and one IdpDetails object used in tandem to define a SAML integration between a customer\'s identity provider and a customer\'s SailPoint instance (i.e., the service provider).
     */
    federationProtocolDetails?: Array<ServiceProviderConfigurationFederationProtocolDetailsInner>;
}

