/**
 * Identity Security Cloud API - Account Activities
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Currently supported requestable object types.
 */
export enum RequestableObjectType {

    AccessProfile = 'ACCESS_PROFILE',

    Role = 'ROLE',

    Entitlement = 'ENTITLEMENT'
}

