/**
 * Identity Security Cloud API - Data Segmentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Value } from './value';
import { ExpressionChildrenInner } from './expressionChildrenInner';


export interface Expression { 
    /**
     * Operator for the expression
     */
    operator?: ExpressionOperatorEnum;
    /**
     * Name for the attribute
     */
    attribute?: string | null;
    value?: Value | null;
    /**
     * List of expressions
     */
    children?: Array<ExpressionChildrenInner> | null;
}
export enum ExpressionOperatorEnum {
    And = 'AND',
    Equals = 'EQUALS'
};



