/**
 * Identity Security Cloud API - Data Segmentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoType } from './dtoType';


export interface Ref { 
    type?: DtoType;
    /**
     * ID of the object to which this reference applies
     */
    id?: string;
}



