/**
 * Identity Security Cloud API - Parameter Storage
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * RFC 6902 JSON Patch operation
 */
export interface ParameterStorageJsonPatch { 
    /**
     * The operation to perform (add, remove, replace, move, copy, test)
     */
    op: ParameterStorageJsonPatchOpEnum;
    /**
     * A JSON-Pointer describing the target location
     */
    path: string;
    /**
     * The value to be used within the operations. Required for add/replace/test.
     */
    value?: any | null;
    /**
     * A JSON-Pointer describing the source location for move/copy.
     */
    from?: string;
}
export enum ParameterStorageJsonPatchOpEnum {
    Add = 'add',
    Remove = 'remove',
    Replace = 'replace',
    Move = 'move',
    Copy = 'copy',
    Test = 'test'
};



