/**
 * NERM API v2025
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DelegationNERMV2025 } from './delegation';


export interface DelegationsGet200ResponseNERMV2025 { 
    delegations?: Array<DelegationNERMV2025>;
}

