/**
 * Identity Security Cloud API - Work Reassignment
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enum list of valid work types that can be selected for a Reassignment Configuration
 */
export enum ConfigTypeEnum {

    AccessRequests = 'ACCESS_REQUESTS',

    Certifications = 'CERTIFICATIONS',

    ManualTasks = 'MANUAL_TASKS',

    GenericApprovals = 'GENERIC_APPROVALS'
}

