/**
 * Identity Security Cloud API - Work Reassignment
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Identity2 } from './identity2';
import { ConfigTypeEnum } from './configTypeEnum';
import { AuditDetails } from './auditDetails';


/**
 * The request body of Reassignment Configuration Details for a specific identity and config type
 */
export interface ConfigurationDetailsResponse { 
    configType?: ConfigTypeEnum;
    targetIdentity?: Identity2;
    /**
     * The date from which to start reassigning work items
     */
    startDate?: string;
    /**
     * The date from which to stop reassigning work items.  If this is an empty string it indicates a permanent reassignment.
     */
    endDate?: string;
    auditDetails?: AuditDetails;
}



