/**
 * Identity Security Cloud API - Identity History
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountStatusChangedStatusChange { 
    /**
     * the previous status of the account
     */
    previousStatus?: AccountStatusChangedStatusChangePreviousStatusEnum;
    /**
     * the new status of the account
     */
    newStatus?: AccountStatusChangedStatusChangeNewStatusEnum;
}
export enum AccountStatusChangedStatusChangePreviousStatusEnum {
    Enabled = 'enabled',
    Disabled = 'disabled',
    Locked = 'locked'
};
export enum AccountStatusChangedStatusChangeNewStatusEnum {
    Enabled = 'enabled',
    Disabled = 'disabled',
    Locked = 'locked'
};



