/**
 * Identity Security Cloud API - Identity History
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributeChange } from './attributeChange';


export interface AttributesChanged { 
    attributeChanges: Array<AttributeChange>;
    /**
     * the event type
     */
    eventType?: string;
    /**
     * the identity id
     */
    identityId?: string;
    /**
     * the date of event
     */
    dateTime?: string;
}

