/**
 * Identity Security Cloud API - Identity History
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IdentityHistoryResponse { 
    /**
     * the identity ID
     */
    id?: string;
    /**
     * the display name of the identity
     */
    displayName?: string;
    /**
     * the date when the identity record was created
     */
    snapshot?: string;
    /**
     * the date when the identity was deleted
     */
    deletedDate?: string;
    /**
     * A map containing the count of each access item
     */
    accessItemCount?: { [key: string]: number; };
    /**
     * A map containing the identity attributes
     */
    attributes?: { [key: string]: any; };
}

