/**
 * Identity Security Cloud API - Identity History
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccessItemRoleResponse } from './accessItemRoleResponse';
import { AccessItemAppResponse } from './accessItemAppResponse';
import { AccessItemEntitlementResponse } from './accessItemEntitlementResponse';
import { AccessItemAccountResponse } from './accessItemAccountResponse';
import { AccessItemAccessProfileResponseAppRefsInner } from './accessItemAccessProfileResponseAppRefsInner';
import { AccessItemAccessProfileResponse } from './accessItemAccessProfileResponse';


export interface ListIdentityAccessItemsV1200ResponseInner { 
    /**
     * the access item id
     */
    id?: string;
    /**
     * the access item type. entitlement in this case
     */
    accessType?: string;
    /**
     * the access item display name
     */
    displayName?: string;
    /**
     * the associated source name if it exists
     */
    sourceName?: string | null;
    /**
     * the entitlement attribute
     */
    attribute: string;
    /**
     * the associated value
     */
    value: string;
    /**
     * the type of entitlement
     */
    type: string;
    /**
     * the description for the role
     */
    description?: string;
    /**
     * the id of the source
     */
    sourceId?: string;
    /**
     * indicates whether the access profile is standalone
     */
    standalone: boolean | null;
    /**
     * indicates whether the entitlement is privileged
     */
    privileged: boolean | null;
    /**
     * indicates whether the entitlement is cloud governed
     */
    cloudGoverned: boolean | null;
    /**
     * the number of entitlements the account will create
     */
    entitlementCount: number;
    /**
     * the list of app ids associated with the access profile
     */
    appRefs: Array<AccessItemAccessProfileResponseAppRefsInner>;
    /**
     * the date the access profile will be assigned to the specified identity, in case requested with a future start date
     */
    startDate?: string | null;
    /**
     * the date the role is no longer assigned to the specified identity
     */
    removeDate?: string;
    /**
     * indicates whether the role is revocable
     */
    revocable: boolean;
    /**
     * the native identifier used to uniquely identify an acccount
     */
    nativeIdentity: string;
    /**
     * the app role id
     */
    appRoleId: string | null;
}

