/**
 * Identity Security Cloud API - SOD Controls
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Referenceinput } from './referenceinput';


export interface Compensatingcontrolupdate { 
    /**
     * The display name of the compensating control.
     */
    name?: string;
    /**
     * A human-readable description of the compensating control.
     */
    description?: string;
    owner?: Referenceinput;
    /**
     * References to additional identities or governance groups that share ownership of the compensating control (maximum 10).
     */
    secondaryOwners?: Array<Referenceinput>;
    /**
     * The type of compensating control that determines how a violation is addressed.
     */
    type?: CompensatingcontrolupdateTypeEnum;
    /**
     * The action performed when the compensating control is applied.
     */
    action?: CompensatingcontrolupdateActionEnum;
    /**
     * The duration after which the applied control expires, expressed as a duration string.
     */
    expiration?: string;
    /**
     * Indicates whether a justification is required when applying this control.
     */
    justificationRequired?: boolean;
    /**
     * Workflow definition ID used when the control action is a workflow.
     */
    workflowID?: string;
}
export enum CompensatingcontrolupdateTypeEnum {
    Mitigation = 'Mitigation',
    Remediation = 'Remediation'
};
export enum CompensatingcontrolupdateActionEnum {
    Workflow = 'Workflow',
    Certification = 'Certification'
};



