/**
 * Identity Security Cloud API - Custom User Levels
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PublicIdentityAttributesInner { 
    /**
     * The attribute key
     */
    key?: string;
    /**
     * Human-readable display name of the attribute
     */
    name?: string;
    /**
     * The attribute value
     */
    value?: string | null;
}

