/**
 * Identity Security Cloud API - Role Propagation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Role Change Propagation Config Response
 */
export interface Rolepropagationconfigresponse { 
    /**
     * Indicates if the Role Change Propagation process is enabled for the tenant
     */
    enabled?: boolean;
    /**
     * The time when Role Change Propagation Process was last enabled on the tenant
     */
    enabledDate?: string;
    /**
     * The time when Role Change Propagation Configuration was first created for the tenant
     */
    createdDate?: string;
    /**
     * The time when Role Change Propagation Config was updated on the tenant
     */
    modifiedDate?: string;
}

