/**
 * Identity Security Cloud API - Icons
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SetIconV1200Response { 
    /**
     * url to file with icon
     */
    icon?: string;
}

