/**
 * Identity Security Cloud API - IAI Access Request Recommendations
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccessRequestRecommendationItem } from './accessRequestRecommendationItem';


export interface AccessRequestRecommendationActionItemDto { 
    /**
     * The identity ID taking the action.
     */
    identityId: string;
    access: AccessRequestRecommendationItem;
}

