/**
 * Identity Security Cloud API - Certification Campaigns
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportType } from './reportType';


export interface CampaignReport { 
    /**
     * SOD policy violation report result DTO type.
     */
    type?: CampaignReportTypeEnum;
    /**
     * SOD policy violation report result ID.
     */
    id?: string;
    /**
     * Human-readable name of the SOD policy violation report result.
     */
    name?: string;
    /**
     * Status of a SOD policy violation report.
     */
    status?: CampaignReportStatusEnum;
    reportType: ReportType;
    /**
     * The most recent date and time this report was run
     */
    readonly lastRunAt?: string;
}
export enum CampaignReportTypeEnum {
    ReportResult = 'REPORT_RESULT'
};
export enum CampaignReportStatusEnum {
    Success = 'SUCCESS',
    Warning = 'WARNING',
    Error = 'ERROR',
    Terminated = 'TERMINATED',
    TempError = 'TEMP_ERROR',
    Pending = 'PENDING'
};



