/**
 * Identity Security Cloud API - Certification Campaigns
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This determines who remediation tasks will be assigned to. Remediation tasks are created for each revoke decision on items in the campaign. The only legal remediator type is \'IDENTITY\', and the chosen identity must be a Role Admin or Org Admin.
 */
export interface Campaign2AllOfRoleCompositionCampaignInfoRemediatorRef { 
    /**
     * Legal Remediator Type
     */
    type: Campaign2AllOfRoleCompositionCampaignInfoRemediatorRefTypeEnum;
    /**
     * The ID of the remediator.
     */
    id: string;
    /**
     * The name of the remediator.
     */
    readonly name?: string;
}
export enum Campaign2AllOfRoleCompositionCampaignInfoRemediatorRefTypeEnum {
    Identity = 'IDENTITY'
};



