/**
 * Identity Security Cloud API - Certification Campaigns
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CampaignCompleteOptions { 
    /**
     * Determines whether to auto-approve(APPROVE) or auto-revoke(REVOKE) upon campaign completion.
     */
    autoCompleteAction?: CampaignCompleteOptionsAutoCompleteActionEnum;
}
export enum CampaignCompleteOptionsAutoCompleteActionEnum {
    Approve = 'APPROVE',
    Revoke = 'REVOKE'
};



