/**
 * Identity Security Cloud API - Certification Campaigns
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Determines which items will be included in this campaign. The default campaign filter is used if this field is left blank.
 */
export interface Campaign2AllOfFilter { 
    /**
     * The ID of whatever type of filter is being used.
     */
    id?: string;
    /**
     * Type of the filter
     */
    type?: Campaign2AllOfFilterTypeEnum;
    /**
     * Name of the filter
     */
    name?: string;
}
export enum Campaign2AllOfFilterTypeEnum {
    CampaignFilter = 'CAMPAIGN_FILTER'
};



