/**
 * Identity Security Cloud API - Certification Campaigns
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Must be set only if the campaign type is SOURCE_OWNER.
 */
export interface Campaign2AllOfSourceOwnerCampaignInfo { 
    /**
     * The list of sources to be included in the campaign.
     */
    sourceIds?: Array<string>;
}

