/**
 * Identity Security Cloud API - Triggers
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccessItemRequestedForDto } from './accessItemRequestedForDto';
import { AccessItemRequesterDto } from './accessItemRequesterDto';
import { AccessRequestPostApprovalRequestedItemsStatusInner } from './accessRequestPostApprovalRequestedItemsStatusInner';


export interface AccessRequestPostApproval { 
    /**
     * The unique ID of the access request.
     */
    accessRequestId: string;
    /**
     * Identities access was requested for.
     */
    requestedFor: Array<AccessItemRequestedForDto>;
    /**
     * Details on the outcome of each access item.
     */
    requestedItemsStatus: Array<AccessRequestPostApprovalRequestedItemsStatusInner>;
    requestedBy: AccessItemRequesterDto;
}

