/**
 * Identity Security Cloud API - Triggers
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Access item requester\'s identity.
 */
export interface AccessItemRequesterDto { 
    /**
     * Access item requester\'s DTO type.
     */
    type?: AccessItemRequesterDtoTypeEnum;
    /**
     * Access item requester\'s identity ID.
     */
    id?: string;
    /**
     * Access item owner\'s human-readable display name.
     */
    name?: string;
}
export enum AccessItemRequesterDtoTypeEnum {
    Identity = 'IDENTITY'
};



