/**
 * Identity Security Cloud API - Triggers
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Identity the account is correlated with.
 */
export interface AccountCorrelatedIdentity { 
    /**
     * DTO type of the identity the account is correlated with.
     */
    type: AccountCorrelatedIdentityTypeEnum;
    /**
     * ID of the identity the account is correlated with.
     */
    id: string;
    /**
     * Display name of the identity the account is correlated with.
     */
    name: string;
}
export enum AccountCorrelatedIdentityTypeEnum {
    Identity = 'IDENTITY'
};



