/**
 * Identity Security Cloud API - Triggers
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CampaignReference { 
    /**
     * The unique ID of the campaign.
     */
    id: string;
    /**
     * The name of the campaign.
     */
    name: string;
    /**
     * The type of object that is being referenced.
     */
    type: CampaignReferenceTypeEnum;
    /**
     * The type of the campaign.
     */
    campaignType: CampaignReferenceCampaignTypeEnum;
    /**
     * The description of the campaign set by the admin who created it.
     */
    description: string | null;
    /**
     * The correlatedStatus of the campaign. Only SOURCE_OWNER campaigns can be Uncorrelated. An Uncorrelated certification campaign only includes Uncorrelated identities (An identity is uncorrelated if it has no accounts on an authoritative source).
     */
    correlatedStatus: CampaignReferenceCorrelatedStatusEnum;
    /**
     * Determines whether comments are required for decisions during certification reviews. You can require comments for all decisions, revoke-only decisions, or no decisions. By default, comments are not required for decisions.
     */
    mandatoryCommentRequirement: CampaignReferenceMandatoryCommentRequirementEnum;
}
export enum CampaignReferenceTypeEnum {
    Campaign = 'CAMPAIGN'
};
export enum CampaignReferenceCampaignTypeEnum {
    Manager = 'MANAGER',
    SourceOwner = 'SOURCE_OWNER',
    Search = 'SEARCH',
    RoleComposition = 'ROLE_COMPOSITION',
    MachineAccount = 'MACHINE_ACCOUNT'
};
export enum CampaignReferenceCorrelatedStatusEnum {
    Correlated = 'CORRELATED',
    Uncorrelated = 'UNCORRELATED'
};
export enum CampaignReferenceMandatoryCommentRequirementEnum {
    AllDecisions = 'ALL_DECISIONS',
    RevokeOnlyDecisions = 'REVOKE_ONLY_DECISIONS',
    NoDecisions = 'NO_DECISIONS'
};



