/**
 * Identity Security Cloud API - Triggers
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MachineIdentityCreatedMachineIdentity } from './machineIdentityCreatedMachineIdentity';


export interface MachineIdentityCreated { 
    /**
     * Type of the event.
     */
    eventType: MachineIdentityCreatedEventTypeEnum;
    machineIdentity: MachineIdentityCreatedMachineIdentity;
}
export enum MachineIdentityCreatedEventTypeEnum {
    MachineIdentityCreated = 'MACHINE_IDENTITY_CREATED'
};



