/**
 * Identity Security Cloud API - Triggers
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MachineIdentitySourceReference } from './machineIdentitySourceReference';
import { MachineIdentityUserEntitlements } from './machineIdentityUserEntitlements';
import { MachineIdentityOwnerReference } from './machineIdentityOwnerReference';


/**
 * Details of the created machine identity.
 */
export interface MachineIdentityCreatedMachineIdentity { 
    /**
     * Unique identifier for the machine identity.
     */
    id: string;
    /**
     * Name of the machine identity.
     */
    name?: string;
    /**
     * Creation timestamp.
     */
    created: string;
    /**
     * Last modified timestamp.
     */
    modified: string;
    /**
     * Associated business application.
     */
    businessApplication?: string;
    /**
     * Description of the machine identity.
     */
    description?: string;
    /**
     * The attributes assigned to the identity.
     */
    attributes?: { [key: string]: any; };
    /**
     * Subtype of the machine identity.
     */
    subtype: MachineIdentityCreatedMachineIdentitySubtypeEnum;
    /**
     * List of owners.
     */
    owners?: Array<MachineIdentityOwnerReference>;
    /**
     * Source identifier.
     */
    sourceId?: string;
    /**
     * UUID of the machine identity.
     */
    uuid?: string;
    /**
     * Native identity value.
     */
    nativeIdentity?: string;
    /**
     * Indicates if manually edited.
     */
    manuallyEdited: boolean;
    /**
     * Indicates if manually created.
     */
    manuallyCreated?: boolean;
    /**
     * Dataset identifier.
     */
    datasetId?: string;
    source?: MachineIdentitySourceReference;
    /**
     * List of user entitlements.
     */
    userEntitlements?: Array<MachineIdentityUserEntitlements>;
    /**
     * Existence status on source.
     */
    existsOnSource?: string;
}
export enum MachineIdentityCreatedMachineIdentitySubtypeEnum {
    AiAgent = 'AI Agent',
    Application = 'Application'
};



