/**
 * Identity Security Cloud API - Triggers
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Provisioning requester\'s identity.
 */
export interface ProvisioningCompletedRequester { 
    /**
     * Provisioning requester\'s DTO type.
     */
    type: ProvisioningCompletedRequesterTypeEnum;
    /**
     * Provisioning requester\'s identity ID.
     */
    id: string;
    /**
     * Provisioning owner\'s human-readable display name.
     */
    name: string;
}
export enum ProvisioningCompletedRequesterTypeEnum {
    Identity = 'IDENTITY'
};



