/**
 * Identity Security Cloud API - Triggers
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SODViolationMitigatedPayloadAppliedControlsInnerControl } from './sODViolationMitigatedPayloadAppliedControlsInnerControl';
import { SODViolationMitigatedPayloadAppliedControlsInnerApplier } from './sODViolationMitigatedPayloadAppliedControlsInnerApplier';
import { ViolationAppliedControlStatus } from './violationAppliedControlStatus';


export interface SODViolationMitigatedPayloadAppliedControlsInner { 
    /**
     * When the control was applied.
     */
    appliedDate?: string;
    applier?: SODViolationMitigatedPayloadAppliedControlsInnerApplier;
    /**
     * Optional comments from the applier.
     */
    comments?: string | null;
    control?: SODViolationMitigatedPayloadAppliedControlsInnerControl;
    /**
     * When this application of the control expires.
     */
    expiration?: string;
    /**
     * ID of the control application record.
     */
    id?: string;
    status?: ViolationAppliedControlStatus;
    /**
     * ID of the violation this application belongs to.
     */
    violation?: string;
    /**
     * Optional workflow correlation ID.
     */
    workflowId?: string | null;
}



