/**
 * Identity Security Cloud API - Triggers
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Identity that applied the control.
 */
export interface SODViolationMitigatedPayloadAppliedControlsInnerApplier { 
    /**
     * Applier ID.
     */
    id?: string;
    /**
     * DTO type of the applier reference.
     */
    type?: SODViolationMitigatedPayloadAppliedControlsInnerApplierTypeEnum;
}
export enum SODViolationMitigatedPayloadAppliedControlsInnerApplierTypeEnum {
    Identity = 'IDENTITY'
};



