/**
 * Identity Security Cloud API - Triggers
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ValidateFilterInputDto { 
    /**
     * Mock input to evaluate filter expression against.
     */
    input: object;
    /**
     * JSONPath filter to conditionally invoke trigger when expression evaluates to true.
     */
    filter: string;
}

