/**
 * Identity Security Cloud API - Roles
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A dimension attribute
 */
export interface DimensionAttribute { 
    /**
     * Name of the attribute
     */
    name?: string;
    /**
     * Display name of the attribute
     */
    displayName?: string;
    /**
     * If an attribute is derived, its value comes from the identity. Otherwise, it can be provided with access request
     */
    derived?: boolean;
}

