/**
 * Identity Security Cloud API - Roles
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdditionalOwnerRef } from './additionalOwnerRef';
import { EntitlementOwner } from './entitlementOwner';
import { PermissionDTO } from './permissionDTO';
import { EntitlementAccessModelMetadata } from './entitlementAccessModelMetadata';
import { EntitlementSource } from './entitlementSource';


export interface Entitlement { 
    /**
     * The entitlement id
     */
    id?: string;
    /**
     * The entitlement name
     */
    name?: string;
    /**
     * The entitlement attribute name
     */
    attribute?: string;
    /**
     * The value of the entitlement
     */
    value?: string;
    /**
     * The object type of the entitlement from the source schema
     */
    sourceSchemaObjectType?: string;
    /**
     * The description of the entitlement
     */
    description?: string | null;
    /**
     * True if the entitlement is privileged
     */
    privileged?: boolean;
    /**
     * True if the entitlement is cloud governed
     */
    cloudGoverned?: boolean;
    /**
     * True if the entitlement is able to be directly requested
     */
    requestable?: boolean;
    owner?: EntitlementOwner | null;
    /**
     * List of additional owner references beyond the primary owner. Each entry may be an identity (IDENTITY) or a governance group (GOVERNANCE_GROUP).
     */
    additionalOwners?: Array<AdditionalOwnerRef> | null;
    /**
     * A map of entitlement fields that have been manually updated. The key is the field name in UPPER_SNAKE_CASE format, and the value is true or false to indicate if the field has been updated.
     */
    manuallyUpdatedFields?: { [key: string]: any; } | null;
    accessModelMetadata?: EntitlementAccessModelMetadata;
    /**
     * Time when the entitlement was created
     */
    created?: string;
    /**
     * Time when the entitlement was last modified
     */
    modified?: string;
    source?: EntitlementSource;
    /**
     * A map of free-form key-value pairs from the source system
     */
    attributes?: { [key: string]: any; };
    /**
     * List of IDs of segments, if any, to which this Entitlement is assigned.
     */
    segments?: Array<string> | null;
    directPermissions?: Array<PermissionDTO>;
}

