/**
 * Identity Security Cloud API - Custom Forms
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormCondition } from './formCondition';
import { FormDefinitionInput } from './formDefinitionInput';
import { FormUsedBy } from './formUsedBy';
import { FormElement } from './formElement';
import { FormOwner } from './formOwner';


export interface FormDefinitionResponse { 
    /**
     * Unique guid identifying the form definition.
     */
    id?: string;
    /**
     * Name of the form definition.
     */
    name?: string;
    /**
     * Form definition\'s description.
     */
    description?: string;
    owner?: FormOwner;
    /**
     * List of objects using the form definition. Whenever a system uses a form, the API reaches out to the form service to record that the system is currently using it.
     */
    usedBy?: Array<FormUsedBy>;
    /**
     * List of form inputs required to create a form-instance object.
     */
    formInput?: Array<FormDefinitionInput>;
    /**
     * List of nested form elements.
     */
    formElements?: Array<FormElement>;
    /**
     * Conditional logic that can dynamically modify the form as the recipient is interacting with it.
     */
    formConditions?: Array<FormCondition>;
    /**
     * Created is the date the form definition was created
     */
    created?: string;
    /**
     * Modified is the last date the form definition was modified
     */
    modified?: string;
}

