/**
 * Identity Security Cloud API - Custom Forms
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormInstanceRecipient } from './formInstanceRecipient';
import { FormCondition } from './formCondition';
import { FormError } from './formError';
import { FormInstanceCreatedBy } from './formInstanceCreatedBy';
import { FormElement } from './formElement';


export interface FormInstanceResponse { 
    /**
     * Unique guid identifying this form instance
     */
    id?: string;
    /**
     * Expire is the maximum amount of time that a form can be in progress. After this time is reached then the form will be moved to a CANCELED state automatically. The user will no longer be able to complete the submission. When a form instance is expires an audit log will be generated for that record
     */
    expire?: string;
    /**
     * State the state of the form instance ASSIGNED FormInstanceStateAssigned IN_PROGRESS FormInstanceStateInProgress SUBMITTED FormInstanceStateSubmitted COMPLETED FormInstanceStateCompleted CANCELLED FormInstanceStateCancelled
     */
    state?: FormInstanceResponseStateEnum;
    /**
     * StandAloneForm is a boolean flag to indicate if this form should be available for users to complete via the standalone form UI or should this only be available to be completed by as an embedded form
     */
    standAloneForm?: boolean;
    /**
     * StandAloneFormURL is the URL where this form may be completed by the designated recipients using the standalone form UI
     */
    standAloneFormUrl?: string;
    createdBy?: FormInstanceCreatedBy;
    /**
     * FormDefinitionID is the id of the form definition that created this form
     */
    formDefinitionId?: string;
    /**
     * FormInput is an object of form input labels to value
     */
    formInput?: { [key: string]: any; } | null;
    /**
     * FormElements is the configuration of the form, this would be a repeat of the fields from the form-config
     */
    formElements?: Array<FormElement>;
    /**
     * FormData is the data provided by the form on submit. The data is in a key -> value map
     */
    formData?: { [key: string]: any; } | null;
    /**
     * FormErrors is an array of form validation errors from the last time the form instance was transitioned to the SUBMITTED state. If the form instance had validation errors then it would be moved to the IN PROGRESS state where the client can retrieve these errors
     */
    formErrors?: Array<FormError>;
    /**
     * FormConditions is the conditional logic that modify the form dynamically modify the form as the recipient is interacting out the form
     */
    formConditions?: Array<FormCondition>;
    /**
     * Created is the date the form instance was assigned
     */
    created?: string;
    /**
     * Modified is the last date the form instance was modified
     */
    modified?: string;
    /**
     * Recipients references to the recipient of a form. The recipients are those who are responsible for filling out a form and completing it
     */
    recipients?: Array<FormInstanceRecipient>;
}
export enum FormInstanceResponseStateEnum {
    Assigned = 'ASSIGNED',
    InProgress = 'IN_PROGRESS',
    Submitted = 'SUBMITTED',
    Completed = 'COMPLETED',
    Cancelled = 'CANCELLED'
};



