/**
 * Identity Security Cloud API - Suggested Entitlement Description
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sed Assignee
 */
export interface SedAssignee { 
    /**
     * Type of assignment When value is PERSONA, the value MUST be SOURCE_OWNER or ENTITLEMENT_OWNER IDENTITY SED_ASSIGNEE_IDENTITY_TYPE GROUP SED_ASSIGNEE_GROUP_TYPE SOURCE_OWNER SED_ASSIGNEE_SOURCE_OWNER_TYPE ENTITLEMENT_OWNER SED_ASSIGNEE_ENTITLEMENT_OWNER_TYPE
     */
    type: SedAssigneeTypeEnum;
    /**
     * Identity or Group identifier Empty when using source/entitlement owner personas
     */
    value?: string;
}
export enum SedAssigneeTypeEnum {
    Identity = 'IDENTITY',
    Group = 'GROUP',
    SourceOwner = 'SOURCE_OWNER',
    EntitlementOwner = 'ENTITLEMENT_OWNER'
};



