/**
 * Identity Security Cloud API - JIT Access
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JITActivationConfigResponse { 
    /**
     * Unique identifier of this JIT activation configuration instance (persisted config id). 
     */
    id: string;
    /**
     * Entitlement IDs governed by JIT activation policy. May be a single-element array when only one entitlement is in scope. 
     */
    entitlementIds?: Array<string>;
    /**
     * Maximum allowed JIT activation duration for a single grant, in minutes; null if unset.
     */
    maxActivationPeriodMins?: number | null;
    /**
     * Maximum allowed extension of an active JIT activation, in minutes; null if unset.
     */
    maxActivationPeriodExtensionMins?: number | null;
    /**
     * Default activation duration offered when a user requests JIT access, in minutes; null if unset.
     */
    defaultMaxActivationPeriodMins?: number | null;
    /**
     * Default extension duration offered for an active JIT activation, in minutes; null if unset.
     */
    defaultMaxActivationPeriodExtensionMins?: number | null;
    /**
     * Email addresses notified for JIT activation events (for example policy owners or a shared mailbox). 
     */
    notificationRecipients?: Array<string>;
    /**
     * Name or key of the email template used for JIT activation notifications; null if unset.
     */
    notificationTemplate?: string | null;
    /**
     * Whether the policy applies to future entitlement assignments.
     */
    applyToFutureAssignments: boolean;
}

