/**
 * Identity Security Cloud API - Scheduled Search
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchScheduleRecipientsInner } from './searchScheduleRecipientsInner';
import { Schedule } from './schedule';


export interface CreateScheduledSearchV1Request { 
    /**
     * The name of the scheduled search. 
     */
    name?: string | null;
    /**
     * The description of the scheduled search. 
     */
    description?: string | null;
    /**
     * The ID of the saved search that will be executed.
     */
    savedSearchId: string;
    /**
     * The date the scheduled search was initially created.
     */
    readonly created?: string | null;
    /**
     * The last date the scheduled search was modified.
     */
    readonly modified?: string | null;
    schedule: Schedule;
    /**
     * A list of identities that should receive the scheduled search report via email.
     */
    recipients: Array<SearchScheduleRecipientsInner>;
    /**
     * Indicates if the scheduled search is enabled. 
     */
    enabled?: boolean;
    /**
     * Indicates if email generation should occur when search returns no results. 
     */
    emailEmptyResults?: boolean;
    /**
     * Indicates if the generated email should include the query and search results preview (which could include PII). 
     */
    displayQueryDetails?: boolean;
}

