/**
 * Identity Security Cloud API - Scheduled Search
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScheduledSearchName { 
    /**
     * The name of the scheduled search. 
     */
    name?: string | null;
    /**
     * The description of the scheduled search. 
     */
    description?: string | null;
}

