/**
 * Identity Security Cloud API - Connector Customizers
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ConnectorCustomizerVersionCreateResponse
 */
export interface ConnectorCustomizerVersionCreateResponse { 
    /**
     * ID of connector customizer.
     */
    customizerID?: string;
    /**
     * ImageID of the connector customizer.
     */
    imageID?: string;
    /**
     * Image version of the connector customizer.
     */
    version?: number;
    /**
     * Date-time when the connector customizer version was created.
     */
    created?: string;
}

