/**
 * Identity Security Cloud API - Multi-Host Integration
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MultiHostIntegrationsConnectorAttributesConnectorFileUploadHistory { 
    /**
     * File name of the connector JAR
     */
    connectorFileNameUploadedDate?: string;
}

