/**
 * Identity Security Cloud API - Multi-Host Integration
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Reference to accounts file for the source.
 */
export interface MultiHostIntegrationsAccountsFile { 
    /**
     * Name of the accounts file.
     */
    name?: string;
    /**
     * The accounts file key.
     */
    key?: string;
    /**
     * Date-time when the file was uploaded
     */
    uploadTime?: string;
    /**
     * Date-time when the accounts file expired.
     */
    expiry?: string;
    /**
     * If this is true, it indicates that the accounts file has expired.
     */
    expired?: boolean;
}

