/**
 * Identity Security Cloud API - Multi-Host Integration
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiHostIntegrationsConnectorAttributesConnectorFileUploadHistory } from './multiHostIntegrationsConnectorAttributesConnectorFileUploadHistory';
import { MultiHostIntegrationsConnectorAttributesMultiHostAttributes } from './multiHostIntegrationsConnectorAttributesMultiHostAttributes';


/**
 * Connector specific configuration. This configuration will differ for Multi-Host Integration type.
 */
export interface MultiHostIntegrationsConnectorAttributes { 
  [key: string]: string | any;


    /**
     * Maximum sources allowed count of a Multi-Host Integration
     */
    maxAllowedSources?: number;
    /**
     * Last upload sources count of a Multi-Host Integration
     */
    lastSourceUploadCount?: number;
    connectorFileUploadHistory?: MultiHostIntegrationsConnectorAttributesConnectorFileUploadHistory;
    /**
     * Multi-Host integration status.
     */
    multihost_status?: MultiHostIntegrationsConnectorAttributesMultihostStatusEnum;
    /**
     * Show account schema
     */
    showAccountSchema?: boolean;
    /**
     * Show entitlement schema
     */
    showEntitlementSchema?: boolean;
    multiHostAttributes?: MultiHostIntegrationsConnectorAttributesMultiHostAttributes;
}
export enum MultiHostIntegrationsConnectorAttributesMultihostStatusEnum {
    Ready = 'ready',
    Processing = 'processing',
    FileUploadInProgress = 'fileUploadInProgress',
    SourceCreationInProgress = 'sourceCreationInProgress',
    AggregationGroupingInProgress = 'aggregationGroupingInProgress',
    AggregationScheduleInProgress = 'aggregationScheduleInProgress',
    DeleteInProgress = 'deleteInProgress',
    DeleteFailed = 'deleteFailed'
};



