/**
 * Identity Security Cloud API - Multi-Host Integration
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Reference to the ManagerCorrelationRule. Only use this rule when a simple filter isn\'t sufficient.
 */
export interface MultiHostIntegrationsManagerCorrelationRule { 
    /**
     * Type of object being referenced.
     */
    type?: MultiHostIntegrationsManagerCorrelationRuleTypeEnum;
    /**
     * Rule ID.
     */
    id?: string;
    /**
     * Rule\'s human-readable display name.
     */
    name?: string;
}
export enum MultiHostIntegrationsManagerCorrelationRuleTypeEnum {
    Rule = 'RULE'
};



