/**
 * Identity Security Cloud API - Privilege Criteria
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrivilegeCriteriaDTOGroupsInner } from './privilegeCriteriaDTOGroupsInner';


export interface PrivilegeCriteriaDTO { 
    /**
     * The Id of the criteria.
     */
    id?: string;
    /**
     * The Id of the source that the criteria is applied to.
     */
    sourceId?: string;
    /**
     * The type of criteria.
     */
    type?: PrivilegeCriteriaDTOTypeEnum;
    /**
     * The logical operator to apply between groups.
     */
    operator?: PrivilegeCriteriaDTOOperatorEnum;
    groups?: Array<PrivilegeCriteriaDTOGroupsInner>;
    /**
     * The privilege level assigned by this criteria.
     */
    privilegeLevel?: PrivilegeCriteriaDTOPrivilegeLevelEnum;
}
export enum PrivilegeCriteriaDTOTypeEnum {
    Custom = 'CUSTOM',
    Connector = 'CONNECTOR',
    SingleLevel = 'SINGLE_LEVEL'
};
export enum PrivilegeCriteriaDTOOperatorEnum {
    And = 'AND',
    Or = 'OR'
};
export enum PrivilegeCriteriaDTOPrivilegeLevelEnum {
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW'
};



