/**
 * Identity Security Cloud API - Access Model Metadata
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccessModelMetadataBulkUpdateResponse { 
    /**
     * ID of the task which is executing the bulk update.
     */
    id?: string;
    /**
     * Type of the bulk update object.
     */
    type?: string;
    /**
     * The status of the bulk update request, only list unfinished request\'s status.
     */
    status?: AccessModelMetadataBulkUpdateResponseStatusEnum;
    /**
     * Time when the bulk update request was created
     */
    created?: string;
}
export enum AccessModelMetadataBulkUpdateResponseStatusEnum {
    Created = 'CREATED',
    PreProcess = 'PRE_PROCESS',
    PreProcessCompleted = 'PRE_PROCESS_COMPLETED',
    PostProcess = 'POST_PROCESS',
    Completed = 'COMPLETED',
    ChunkPending = 'CHUNK_PENDING',
    ChunkProcessing = 'CHUNK_PROCESSING',
    ReProcessing = 'RE_PROCESSING',
    PreProcessFailed = 'PRE_PROCESS_FAILED',
    Failed = 'FAILED'
};



