/**
 * Identity Security Cloud API - Access Model Metadata
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The nested aggregation object.
 */
export interface NestedAggregation { 
    /**
     * The name of the nested aggregate to be included in the result.
     */
    name: string;
    /**
     * The type of the nested object.
     */
    type: string;
}

